steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${TAG_NAME}',
        '--build-arg',
        'NEXT_PUBLIC_APP_URL=${_NEXT_PUBLIC_APP_URL}',
        '--build-arg',
        'NEXT_PUBLIC_ENVIRONMENT=${_NEXT_PUBLIC_ENVIRONMENT}',
        '.',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${TAG_NAME}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${TAG_NAME}',
        '--set-env-vars',
        'API_URL=${_API_URL},APP_BASE_URL=${_NEXT_PUBLIC_APP_URL},AUTH0_DOMAIN=${_AUTH0_DOMAIN},AUTH0_CLIENT_ID=${_AUTH0_CLIENT_ID},AUTH0_AUDIENCE=${_AUTH0_AUDIENCE}',
        '--set-secrets',
        'AUTH0_SECRET=${_AUTH0_SECRET_NAME}:latest,AUTH0_CLIENT_SECRET=${_AUTH0_CLIENT_SECRET_NAME}:latest',
        '--region',
        '${_REGION}',
        '--service-account',
        '${_SERVICE_ACCOUNT}@$PROJECT_ID.iam.gserviceaccount.com',
        '--max-instances',
        '${_MAX_INSTANCES}',
      ]

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${TAG_NAME}'

substitutions:
  _SERVICE_NAME: knodeledge-ui
  _REGION: us-central1
  _REPOSITORY: knodeledge-ui-repository
  _SERVICE_ACCOUNT: knodeledge-ui-identity
  _MAX_INSTANCES: '1'
  _AUTH0_SECRET_NAME: auth0-secret
  _AUTH0_CLIENT_SECRET_NAME: auth0-client-secret
  _NEXT_PUBLIC_ENVIRONMENT: <TRIGGER WILL REPLACE THIS>
  _NEXT_PUBLIC_APP_URL: <TRIGGER WILL REPLACE THIS>
  _API_URL: <TRIGGER WILL REPLACE THIS>
  _AUTH0_DOMAIN: <TRIGGER WILL REPLACE THIS>
  _AUTH0_CLIENT_ID: <TRIGGER WILL REPLACE THIS>
  _AUTH0_AUDIENCE: <TRIGGER WILL REPLACE THIS>

options:
  logging: CLOUD_LOGGING_ONLY
