/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  ApplicationErrorResponse,
  ChapterCreateErrorResponse,
  ChapterCreateRequest,
  ChapterCreateResponse,
  ChapterListErrorResponse,
  ChapterListRequest,
  ChapterListResponse,
  ChapterUpdateErrorResponse,
  ChapterUpdateRequest,
  ChapterUpdateResponse,
} from '../models/index';
import {
  ApplicationErrorResponseFromJSON,
  ApplicationErrorResponseToJSON,
  ChapterCreateErrorResponseFromJSON,
  ChapterCreateErrorResponseToJSON,
  ChapterCreateRequestFromJSON,
  ChapterCreateRequestToJSON,
  ChapterCreateResponseFromJSON,
  ChapterCreateResponseToJSON,
  ChapterListErrorResponseFromJSON,
  ChapterListErrorResponseToJSON,
  ChapterListRequestFromJSON,
  ChapterListRequestToJSON,
  ChapterListResponseFromJSON,
  ChapterListResponseToJSON,
  ChapterUpdateErrorResponseFromJSON,
  ChapterUpdateErrorResponseToJSON,
  ChapterUpdateRequestFromJSON,
  ChapterUpdateRequestToJSON,
  ChapterUpdateResponseFromJSON,
  ChapterUpdateResponseToJSON,
} from '../models/index';

export interface ChaptersCreateRequest {
  chapterCreateRequest?: ChapterCreateRequest;
}

export interface ChaptersListRequest {
  chapterListRequest?: ChapterListRequest;
}

export interface ChaptersUpdateRequest {
  chapterUpdateRequest?: ChapterUpdateRequest;
}

/**
 *
 */
export class ChaptersApi extends runtime.BaseAPI {
  /**
   * Create new Chapter
   */
  async chaptersCreateRaw(
    requestParameters: ChaptersCreateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChapterCreateResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/chapters/create`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChapterCreateRequestToJSON(requestParameters['chapterCreateRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ChapterCreateResponseFromJSON(jsonValue));
  }

  /**
   * Create new Chapter
   */
  async chaptersCreate(
    requestParameters: ChaptersCreateRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChapterCreateResponse> {
    const response = await this.chaptersCreateRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get list of chapters for a project
   */
  async chaptersListRaw(
    requestParameters: ChaptersListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChapterListResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/chapters/list`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChapterListRequestToJSON(requestParameters['chapterListRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ChapterListResponseFromJSON(jsonValue));
  }

  /**
   * Get list of chapters for a project
   */
  async chaptersList(
    requestParameters: ChaptersListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChapterListResponse> {
    const response = await this.chaptersListRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update chapter
   */
  async chaptersUpdateRaw(
    requestParameters: ChaptersUpdateRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChapterUpdateResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/chapters/update`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ChapterUpdateRequestToJSON(requestParameters['chapterUpdateRequest']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ChapterUpdateResponseFromJSON(jsonValue));
  }

  /**
   * Update chapter
   */
  async chaptersUpdate(
    requestParameters: ChaptersUpdateRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChapterUpdateResponse> {
    const response = await this.chaptersUpdateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
