/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ApplicationErrorResponse, HelloWorldRequest, HelloWorldResponse } from '../models/index';
import {
  ApplicationErrorResponseFromJSON,
  ApplicationErrorResponseToJSON,
  HelloWorldRequestFromJSON,
  HelloWorldRequestToJSON,
  HelloWorldResponseFromJSON,
  HelloWorldResponseToJSON,
} from '../models/index';

export interface GetRequest {
  helloWorldRequest?: HelloWorldRequest;
}

/**
 *
 */
export class HelloWorldApi extends runtime.BaseAPI {
  /**
   * Hello World
   */
  async getRaw(
    requestParameters: GetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HelloWorldResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/hello-world`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: HelloWorldRequestToJSON(requestParameters.helloWorldRequest),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => HelloWorldResponseFromJSON(jsonValue));
  }

  /**
   * Hello World
   */
  async get(
    requestParameters: GetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HelloWorldResponse> {
    const response = await this.getRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
