/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Common error response for application
 * @export
 * @interface ApplicationErrorResponse
 */
export interface ApplicationErrorResponse {
  /**
   * Error message
   * @type {string}
   * @memberof ApplicationErrorResponse
   */
  message: string;
}

/**
 * Check if a given object implements the ApplicationErrorResponse interface.
 */
export function instanceOfApplicationErrorResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function ApplicationErrorResponseFromJSON(json: any): ApplicationErrorResponse {
  return ApplicationErrorResponseFromJSONTyped(json, false);
}

export function ApplicationErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApplicationErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function ApplicationErrorResponseToJSON(value?: ApplicationErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
  };
}
