/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';

/**
 * Error Response Body for Chapter List API
 * @export
 * @interface ChapterListErrorResponse
 */
export interface ChapterListErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterListErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterListErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterListErrorResponse
   */
  project?: ProjectOnlyIdError;
}

/**
 * Check if a given object implements the ChapterListErrorResponse interface.
 */
export function instanceOfChapterListErrorResponse(value: object): value is ChapterListErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ChapterListErrorResponseFromJSON(json: any): ChapterListErrorResponse {
  return ChapterListErrorResponseFromJSONTyped(json, false);
}

export function ChapterListErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterListErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
  };
}

export function ChapterListErrorResponseToJSON(json: any): ChapterListErrorResponse {
  return ChapterListErrorResponseToJSONTyped(json, false);
}

export function ChapterListErrorResponseToJSONTyped(
  value?: ChapterListErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
  };
}
