/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for ChapterOnlyId object
 * @export
 * @interface ChapterOnlyIdError
 */
export interface ChapterOnlyIdError {
  /**
   * Error message for project ID
   * @type {string}
   * @memberof ChapterOnlyIdError
   */
  id?: string;
}

/**
 * Check if a given object implements the ChapterOnlyIdError interface.
 */
export function instanceOfChapterOnlyIdError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChapterOnlyIdErrorFromJSON(json: any): ChapterOnlyIdError {
  return ChapterOnlyIdErrorFromJSONTyped(json, false);
}

export function ChapterOnlyIdErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOnlyIdError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function ChapterOnlyIdErrorToJSON(value?: ChapterOnlyIdError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
