/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterWithoutAutofieldError } from './ChapterWithoutAutofieldError';
import {
  ChapterWithoutAutofieldErrorFromJSON,
  ChapterWithoutAutofieldErrorFromJSONTyped,
  ChapterWithoutAutofieldErrorToJSON,
} from './ChapterWithoutAutofieldError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Chapter Create API
 * @export
 * @interface ChapterCreateErrorResponse
 */
export interface ChapterCreateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterCreateErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterCreateErrorResponse
   */
  user: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterCreateErrorResponse
   */
  project: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterWithoutAutofieldError}
   * @memberof ChapterCreateErrorResponse
   */
  chapter: ChapterWithoutAutofieldError;
}

/**
 * Check if a given object implements the ChapterCreateErrorResponse interface.
 */
export function instanceOfChapterCreateErrorResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'chapter' in value;

  return isInstance;
}

export function ChapterCreateErrorResponseFromJSON(json: any): ChapterCreateErrorResponse {
  return ChapterCreateErrorResponseFromJSONTyped(json, false);
}

export function ChapterCreateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterCreateErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: UserOnlyIdErrorFromJSON(json['user']),
    project: ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: ChapterWithoutAutofieldErrorFromJSON(json['chapter']),
  };
}

export function ChapterCreateErrorResponseToJSON(value?: ChapterCreateErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterWithoutAutofieldErrorToJSON(value.chapter),
  };
}
