/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { Chapter } from './Chapter';
import { ChapterFromJSON, ChapterFromJSONTyped, ChapterToJSON, ChapterToJSONTyped } from './Chapter';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Chapter Update API
 * @export
 * @interface ChapterUpdateRequest
 */
export interface ChapterUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ChapterUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof ChapterUpdateRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {Chapter}
   * @memberof ChapterUpdateRequest
   */
  chapter: Chapter;
}

/**
 * Check if a given object implements the ChapterUpdateRequest interface.
 */
export function instanceOfChapterUpdateRequest(value: object): value is ChapterUpdateRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  if (!('chapter' in value) || value['chapter'] === undefined) return false;
  return true;
}

export function ChapterUpdateRequestFromJSON(json: any): ChapterUpdateRequest {
  return ChapterUpdateRequestFromJSONTyped(json, false);
}

export function ChapterUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterFromJSON(json['chapter']),
  };
}

export function ChapterUpdateRequestToJSON(json: any): ChapterUpdateRequest {
  return ChapterUpdateRequestToJSONTyped(json, false);
}

export function ChapterUpdateRequestToJSONTyped(
  value?: ChapterUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
    chapter: ChapterToJSON(value['chapter']),
  };
}
