/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for ChapterWithoutAutofield object
 * @export
 * @interface ChapterWithoutAutofieldError
 */
export interface ChapterWithoutAutofieldError {
  /**
   * Error message for chapter name
   * @type {string}
   * @memberof ChapterWithoutAutofieldError
   */
  name?: string;
  /**
   * Error message for chapter number
   * @type {string}
   * @memberof ChapterWithoutAutofieldError
   */
  number?: string;
}

/**
 * Check if a given object implements the ChapterWithoutAutofieldError interface.
 */
export function instanceOfChapterWithoutAutofieldError(value: object): value is ChapterWithoutAutofieldError {
  return true;
}

export function ChapterWithoutAutofieldErrorFromJSON(json: any): ChapterWithoutAutofieldError {
  return ChapterWithoutAutofieldErrorFromJSONTyped(json, false);
}

export function ChapterWithoutAutofieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterWithoutAutofieldError {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    number: json['number'] == null ? undefined : json['number'],
  };
}

export function ChapterWithoutAutofieldErrorToJSON(json: any): ChapterWithoutAutofieldError {
  return ChapterWithoutAutofieldErrorToJSONTyped(json, false);
}

export function ChapterWithoutAutofieldErrorToJSONTyped(
  value?: ChapterWithoutAutofieldError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    number: value['number'],
  };
}
