/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterWithSections } from './ChapterWithSections';
import {
  ChapterWithSectionsFromJSON,
  ChapterWithSectionsFromJSONTyped,
  ChapterWithSectionsToJSON,
  ChapterWithSectionsToJSONTyped,
} from './ChapterWithSections';

/**
 * Response Body for Chapter Update API
 * @export
 * @interface ChapterUpdateResponse
 */
export interface ChapterUpdateResponse {
  /**
   *
   * @type {ChapterWithSections}
   * @memberof ChapterUpdateResponse
   */
  chapter: ChapterWithSections;
}

/**
 * Check if a given object implements the ChapterUpdateResponse interface.
 */
export function instanceOfChapterUpdateResponse(value: object): value is ChapterUpdateResponse {
  if (!('chapter' in value) || value['chapter'] === undefined) return false;
  return true;
}

export function ChapterUpdateResponseFromJSON(json: any): ChapterUpdateResponse {
  return ChapterUpdateResponseFromJSONTyped(json, false);
}

export function ChapterUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterUpdateResponse {
  if (json == null) {
    return json;
  }
  return {
    chapter: ChapterWithSectionsFromJSON(json['chapter']),
  };
}

export function ChapterUpdateResponseToJSON(json: any): ChapterUpdateResponse {
  return ChapterUpdateResponseToJSONTyped(json, false);
}

export function ChapterUpdateResponseToJSONTyped(
  value?: ChapterUpdateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chapter: ChapterWithSectionsToJSON(value['chapter']),
  };
}
