/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Chapter List API
 * @export
 * @interface ChapterListErrorResponse
 */
export interface ChapterListErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterListErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterListErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterListErrorResponse
   */
  project?: ProjectOnlyIdError;
}

/**
 * Check if a given object implements the ChapterListErrorResponse interface.
 */
export function instanceOfChapterListErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChapterListErrorResponseFromJSON(json: any): ChapterListErrorResponse {
  return ChapterListErrorResponseFromJSONTyped(json, false);
}

export function ChapterListErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterListErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
  };
}

export function ChapterListErrorResponseToJSON(value?: ChapterListErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
  };
}
