/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterWithSections } from './ChapterWithSections';
import {
  ChapterWithSectionsFromJSON,
  ChapterWithSectionsFromJSONTyped,
  ChapterWithSectionsToJSON,
} from './ChapterWithSections';

/**
 * Response Body for Chapter List API
 * @export
 * @interface ChapterListResponse
 */
export interface ChapterListResponse {
  /**
   *
   * @type {Array<ChapterWithSections>}
   * @memberof ChapterListResponse
   */
  chapters: Array<ChapterWithSections>;
}

/**
 * Check if a given object implements the ChapterListResponse interface.
 */
export function instanceOfChapterListResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'chapters' in value;

  return isInstance;
}

export function ChapterListResponseFromJSON(json: any): ChapterListResponse {
  return ChapterListResponseFromJSONTyped(json, false);
}

export function ChapterListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    chapters: (json['chapters'] as Array<any>).map(ChapterWithSectionsFromJSON),
  };
}

export function ChapterListResponseToJSON(value?: ChapterListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    chapters: (value.chapters as Array<any>).map(ChapterWithSectionsToJSON),
  };
}
