/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Response Body for Chapter List API
 * @export
 * @interface ChapterListErrorResponse
 */
export interface ChapterListErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterListErrorResponse
   */
  message: string;
  /**
   * Error message for user ID
   * @type {string}
   * @memberof ChapterListErrorResponse
   */
  userId?: string;
  /**
   * Error message for project ID
   * @type {string}
   * @memberof ChapterListErrorResponse
   */
  projectId?: string;
}

/**
 * Check if a given object implements the ChapterListErrorResponse interface.
 */
export function instanceOfChapterListErrorResponse(value: object): value is ChapterListErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ChapterListErrorResponseFromJSON(json: any): ChapterListErrorResponse {
  return ChapterListErrorResponseFromJSONTyped(json, false);
}

export function ChapterListErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterListErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    userId: json['userId'] == null ? undefined : json['userId'],
    projectId: json['projectId'] == null ? undefined : json['projectId'],
  };
}

export function ChapterListErrorResponseToJSON(json: any): ChapterListErrorResponse {
  return ChapterListErrorResponseToJSONTyped(json, false);
}

export function ChapterListErrorResponseToJSONTyped(
  value?: ChapterListErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    userId: value['userId'],
    projectId: value['projectId'],
  };
}
