/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request Paramemters for Chapter List API
 * @export
 * @interface ChapterListRequest
 */
export interface ChapterListRequest {
  /**
   * User ID
   * @type {string}
   * @memberof ChapterListRequest
   */
  userId: string;
  /**
   * Auto-generated project ID
   * @type {string}
   * @memberof ChapterListRequest
   */
  projectId: string;
}

/**
 * Check if a given object implements the ChapterListRequest interface.
 */
export function instanceOfChapterListRequest(value: object): value is ChapterListRequest {
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('projectId' in value) || value['projectId'] === undefined) return false;
  return true;
}

export function ChapterListRequestFromJSON(json: any): ChapterListRequest {
  return ChapterListRequestFromJSONTyped(json, false);
}

export function ChapterListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterListRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json['userId'],
    projectId: json['projectId'],
  };
}

export function ChapterListRequestToJSON(json: any): ChapterListRequest {
  return ChapterListRequestToJSONTyped(json, false);
}

export function ChapterListRequestToJSONTyped(
  value?: ChapterListRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value['userId'],
    projectId: value['projectId'],
  };
}
