/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
  ChapterOnlyIdErrorToJSONTyped,
} from './ChapterOnlyIdError';

/**
 * Error Response Body for Chapter Delete API
 * @export
 * @interface ChapterDeleteErrorResponse
 */
export interface ChapterDeleteErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterDeleteErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterDeleteErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterDeleteErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof ChapterDeleteErrorResponse
   */
  chapter?: ChapterOnlyIdError;
}

/**
 * Check if a given object implements the ChapterDeleteErrorResponse interface.
 */
export function instanceOfChapterDeleteErrorResponse(value: object): value is ChapterDeleteErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ChapterDeleteErrorResponseFromJSON(json: any): ChapterDeleteErrorResponse {
  return ChapterDeleteErrorResponseFromJSONTyped(json, false);
}

export function ChapterDeleteErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterDeleteErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: json['chapter'] == null ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
  };
}

export function ChapterDeleteErrorResponseToJSON(json: any): ChapterDeleteErrorResponse {
  return ChapterDeleteErrorResponseToJSONTyped(json, false);
}

export function ChapterDeleteErrorResponseToJSONTyped(
  value?: ChapterDeleteErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    chapter: ChapterOnlyIdErrorToJSON(value['chapter']),
  };
}
