/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Chapter List API
 * @export
 * @interface ChapterListRequest
 */
export interface ChapterListRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ChapterListRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof ChapterListRequest
   */
  project: ProjectOnlyId;
}

/**
 * Check if a given object implements the ChapterListRequest interface.
 */
export function instanceOfChapterListRequest(value: object): value is ChapterListRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ChapterListRequestFromJSON(json: any): ChapterListRequest {
  return ChapterListRequestFromJSONTyped(json, false);
}

export function ChapterListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterListRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
  };
}

export function ChapterListRequestToJSON(json: any): ChapterListRequest {
  return ChapterListRequestToJSONTyped(json, false);
}

export function ChapterListRequestToJSONTyped(
  value?: ChapterListRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
  };
}
