/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterError } from './ChapterError';
import { ChapterErrorFromJSON, ChapterErrorFromJSONTyped, ChapterErrorToJSON } from './ChapterError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Chapter Create API
 * @export
 * @interface ChapterUpdateErrorResponse
 */
export interface ChapterUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterUpdateErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterUpdateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterUpdateErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterError}
   * @memberof ChapterUpdateErrorResponse
   */
  chapter?: ChapterError;
}

/**
 * Check if a given object implements the ChapterUpdateErrorResponse interface.
 */
export function instanceOfChapterUpdateErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChapterUpdateErrorResponseFromJSON(json: any): ChapterUpdateErrorResponse {
  return ChapterUpdateErrorResponseFromJSONTyped(json, false);
}

export function ChapterUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterUpdateErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: !exists(json, 'chapter') ? undefined : ChapterErrorFromJSON(json['chapter']),
  };
}

export function ChapterUpdateErrorResponseToJSON(value?: ChapterUpdateErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterErrorToJSON(value.chapter),
  };
}
