/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for ChapterWithoutAutofield object
 * @export
 * @interface ChapterWithoutAutofieldError
 */
export interface ChapterWithoutAutofieldError {
  /**
   * Error message for chapter name
   * @type {string}
   * @memberof ChapterWithoutAutofieldError
   */
  name?: string;
  /**
   * Error message for chapter number
   * @type {string}
   * @memberof ChapterWithoutAutofieldError
   */
  number?: string;
}

/**
 * Check if a given object implements the ChapterWithoutAutofieldError interface.
 */
export function instanceOfChapterWithoutAutofieldError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChapterWithoutAutofieldErrorFromJSON(json: any): ChapterWithoutAutofieldError {
  return ChapterWithoutAutofieldErrorFromJSONTyped(json, false);
}

export function ChapterWithoutAutofieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterWithoutAutofieldError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    number: !exists(json, 'number') ? undefined : json['number'],
  };
}

export function ChapterWithoutAutofieldErrorToJSON(value?: ChapterWithoutAutofieldError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    number: value.number,
  };
}
