/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chapter object with only ID
 * @export
 * @interface ChapterOnlyId
 */
export interface ChapterOnlyId {
  /**
   * Auto-generated chapter ID
   * @type {string}
   * @memberof ChapterOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the ChapterOnlyId interface.
 */
export function instanceOfChapterOnlyId(value: object): value is ChapterOnlyId {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function ChapterOnlyIdFromJSON(json: any): ChapterOnlyId {
  return ChapterOnlyIdFromJSONTyped(json, false);
}

export function ChapterOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOnlyId {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ChapterOnlyIdToJSON(json: any): ChapterOnlyId {
  return ChapterOnlyIdToJSONTyped(json, false);
}

export function ChapterOnlyIdToJSONTyped(value?: ChapterOnlyId | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
