/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { ChapterError } from './ChapterError';
import {
  ChapterErrorFromJSON,
  ChapterErrorFromJSONTyped,
  ChapterErrorToJSON,
  ChapterErrorToJSONTyped,
} from './ChapterError';

/**
 * Error Response Body for Chapter Create API
 * @export
 * @interface ChapterUpdateErrorResponse
 */
export interface ChapterUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ChapterUpdateErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ChapterUpdateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof ChapterUpdateErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterError}
   * @memberof ChapterUpdateErrorResponse
   */
  chapter?: ChapterError;
}

/**
 * Check if a given object implements the ChapterUpdateErrorResponse interface.
 */
export function instanceOfChapterUpdateErrorResponse(value: object): value is ChapterUpdateErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ChapterUpdateErrorResponseFromJSON(json: any): ChapterUpdateErrorResponse {
  return ChapterUpdateErrorResponseFromJSONTyped(json, false);
}

export function ChapterUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ChapterUpdateErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: json['chapter'] == null ? undefined : ChapterErrorFromJSON(json['chapter']),
  };
}

export function ChapterUpdateErrorResponseToJSON(json: any): ChapterUpdateErrorResponse {
  return ChapterUpdateErrorResponseToJSONTyped(json, false);
}

export function ChapterUpdateErrorResponseToJSONTyped(
  value?: ChapterUpdateErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    chapter: ChapterErrorToJSON(value['chapter']),
  };
}
