/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Chapter } from './Chapter';
import { ChapterFromJSON, ChapterFromJSONTyped, ChapterToJSON } from './Chapter';
import type { ProjectOnlyId } from './ProjectOnlyId';
import { ProjectOnlyIdFromJSON, ProjectOnlyIdFromJSONTyped, ProjectOnlyIdToJSON } from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Chapter Update API
 * @export
 * @interface ChapterUpdateRequest
 */
export interface ChapterUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ChapterUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof ChapterUpdateRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {Chapter}
   * @memberof ChapterUpdateRequest
   */
  chapter: Chapter;
}

/**
 * Check if a given object implements the ChapterUpdateRequest interface.
 */
export function instanceOfChapterUpdateRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'chapter' in value;

  return isInstance;
}

export function ChapterUpdateRequestFromJSON(json: any): ChapterUpdateRequest {
  return ChapterUpdateRequestFromJSONTyped(json, false);
}

export function ChapterUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterUpdateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterFromJSON(json['chapter']),
  };
}

export function ChapterUpdateRequestToJSON(value?: ChapterUpdateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectOnlyIdToJSON(value.project),
    chapter: ChapterToJSON(value.chapter),
  };
}
