/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for Chapter object
 * @export
 * @interface ChapterError
 */
export interface ChapterError {
  /**
   * Error message for chapter ID
   * @type {string}
   * @memberof ChapterError
   */
  id?: string;
  /**
   * Error message for chapter name
   * @type {string}
   * @memberof ChapterError
   */
  name?: string;
  /**
   * Error message for chapter number
   * @type {string}
   * @memberof ChapterError
   */
  number?: string;
}

/**
 * Check if a given object implements the ChapterError interface.
 */
export function instanceOfChapterError(value: object): value is ChapterError {
  return true;
}

export function ChapterErrorFromJSON(json: any): ChapterError {
  return ChapterErrorFromJSONTyped(json, false);
}

export function ChapterErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    number: json['number'] == null ? undefined : json['number'],
  };
}

export function ChapterErrorToJSON(json: any): ChapterError {
  return ChapterErrorToJSONTyped(json, false);
}

export function ChapterErrorToJSONTyped(value?: ChapterError | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    number: value['number'],
  };
}
