/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Chapter object with only ID
 * @export
 * @interface ChapterOnlyId
 */
export interface ChapterOnlyId {
  /**
   * Auto-generated chapter ID
   * @type {string}
   * @memberof ChapterOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the ChapterOnlyId interface.
 */
export function instanceOfChapterOnlyId(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ChapterOnlyIdFromJSON(json: any): ChapterOnlyId {
  return ChapterOnlyIdFromJSONTyped(json, false);
}

export function ChapterOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOnlyId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ChapterOnlyIdToJSON(value?: ChapterOnlyId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
