/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Chapter object without auto-generated fields
 * @export
 * @interface ChapterWithoutAutofield
 */
export interface ChapterWithoutAutofield {
  /**
   * Chapter name
   * @type {string}
   * @memberof ChapterWithoutAutofield
   */
  name: string;
  /**
   * Chapter number
   * @type {number}
   * @memberof ChapterWithoutAutofield
   */
  number: number;
}

/**
 * Check if a given object implements the ChapterWithoutAutofield interface.
 */
export function instanceOfChapterWithoutAutofield(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'number' in value;

  return isInstance;
}

export function ChapterWithoutAutofieldFromJSON(json: any): ChapterWithoutAutofield {
  return ChapterWithoutAutofieldFromJSONTyped(json, false);
}

export function ChapterWithoutAutofieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterWithoutAutofield {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    number: json['number'],
  };
}

export function ChapterWithoutAutofieldToJSON(value?: ChapterWithoutAutofield | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    number: value.number,
  };
}
