/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Chapter object without auto-generated fields
 * @export
 * @interface ChapterWithoutAutofield
 */
export interface ChapterWithoutAutofield {
  /**
   * Chapter name
   * @type {string}
   * @memberof ChapterWithoutAutofield
   */
  name: string;
  /**
   * Chapter number
   * @type {number}
   * @memberof ChapterWithoutAutofield
   */
  number: number;
}

/**
 * Check if a given object implements the ChapterWithoutAutofield interface.
 */
export function instanceOfChapterWithoutAutofield(value: object): value is ChapterWithoutAutofield {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('number' in value) || value['number'] === undefined) return false;
  return true;
}

export function ChapterWithoutAutofieldFromJSON(json: any): ChapterWithoutAutofield {
  return ChapterWithoutAutofieldFromJSONTyped(json, false);
}

export function ChapterWithoutAutofieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterWithoutAutofield {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    number: json['number'],
  };
}

export function ChapterWithoutAutofieldToJSON(json: any): ChapterWithoutAutofield {
  return ChapterWithoutAutofieldToJSONTyped(json, false);
}

export function ChapterWithoutAutofieldToJSONTyped(
  value?: ChapterWithoutAutofield | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    number: value['number'],
  };
}
