/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for Chapter object
 * @export
 * @interface ChapterError
 */
export interface ChapterError {
  /**
   * Error message for chapter ID
   * @type {string}
   * @memberof ChapterError
   */
  id?: string;
  /**
   * Error message for chapter name
   * @type {string}
   * @memberof ChapterError
   */
  name?: string;
  /**
   * Error message for chapter number
   * @type {string}
   * @memberof ChapterError
   */
  number?: string;
}

/**
 * Check if a given object implements the ChapterError interface.
 */
export function instanceOfChapterError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ChapterErrorFromJSON(json: any): ChapterError {
  return ChapterErrorFromJSONTyped(json, false);
}

export function ChapterErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    number: !exists(json, 'number') ? undefined : json['number'],
  };
}

export function ChapterErrorToJSON(value?: ChapterError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    number: value.number,
  };
}
