/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for ChapterOnlyId object
 * @export
 * @interface ChapterOnlyIdError
 */
export interface ChapterOnlyIdError {
  /**
   * Error message for chapter ID
   * @type {string}
   * @memberof ChapterOnlyIdError
   */
  id?: string;
}

/**
 * Check if a given object implements the ChapterOnlyIdError interface.
 */
export function instanceOfChapterOnlyIdError(value: object): value is ChapterOnlyIdError {
  return true;
}

export function ChapterOnlyIdErrorFromJSON(json: any): ChapterOnlyIdError {
  return ChapterOnlyIdErrorFromJSONTyped(json, false);
}

export function ChapterOnlyIdErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterOnlyIdError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
  };
}

export function ChapterOnlyIdErrorToJSON(json: any): ChapterOnlyIdError {
  return ChapterOnlyIdErrorToJSONTyped(json, false);
}

export function ChapterOnlyIdErrorToJSONTyped(
  value?: ChapterOnlyIdError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
