/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterWithSections } from './ChapterWithSections';
import {
  ChapterWithSectionsFromJSON,
  ChapterWithSectionsFromJSONTyped,
  ChapterWithSectionsToJSON,
  ChapterWithSectionsToJSONTyped,
} from './ChapterWithSections';

/**
 * Response Body for Chapter List API
 * @export
 * @interface ChapterListResponse
 */
export interface ChapterListResponse {
  /**
   *
   * @type {Array<ChapterWithSections>}
   * @memberof ChapterListResponse
   */
  chapters: Array<ChapterWithSections>;
}

/**
 * Check if a given object implements the ChapterListResponse interface.
 */
export function instanceOfChapterListResponse(value: object): value is ChapterListResponse {
  if (!('chapters' in value) || value['chapters'] === undefined) return false;
  return true;
}

export function ChapterListResponseFromJSON(json: any): ChapterListResponse {
  return ChapterListResponseFromJSONTyped(json, false);
}

export function ChapterListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterListResponse {
  if (json == null) {
    return json;
  }
  return {
    chapters: (json['chapters'] as Array<any>).map(ChapterWithSectionsFromJSON),
  };
}

export function ChapterListResponseToJSON(json: any): ChapterListResponse {
  return ChapterListResponseToJSONTyped(json, false);
}

export function ChapterListResponseToJSONTyped(
  value?: ChapterListResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    chapters: (value['chapters'] as Array<any>).map(ChapterWithSectionsToJSON),
  };
}
