/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Graph } from './Graph';
import { GraphFromJSON, GraphFromJSONTyped, GraphToJSON, GraphToJSONTyped } from './Graph';

/**
 * Request Body for Graph Find API
 * @export
 * @interface GraphFindResponse
 */
export interface GraphFindResponse {
  /**
   *
   * @type {Graph}
   * @memberof GraphFindResponse
   */
  graph: Graph;
}

/**
 * Check if a given object implements the GraphFindResponse interface.
 */
export function instanceOfGraphFindResponse(value: object): value is GraphFindResponse {
  if (!('graph' in value) || value['graph'] === undefined) return false;
  return true;
}

export function GraphFindResponseFromJSON(json: any): GraphFindResponse {
  return GraphFindResponseFromJSONTyped(json, false);
}

export function GraphFindResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphFindResponse {
  if (json == null) {
    return json;
  }
  return {
    graph: GraphFromJSON(json['graph']),
  };
}

export function GraphFindResponseToJSON(json: any): GraphFindResponse {
  return GraphFindResponseToJSONTyped(json, false);
}

export function GraphFindResponseToJSONTyped(
  value?: GraphFindResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value['graph']),
  };
}
