/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionOnlyIdError } from './SectionOnlyIdError';
import {
  SectionOnlyIdErrorFromJSON,
  SectionOnlyIdErrorFromJSONTyped,
  SectionOnlyIdErrorToJSON,
  SectionOnlyIdErrorToJSONTyped,
} from './SectionOnlyIdError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
  ChapterOnlyIdErrorToJSONTyped,
} from './ChapterOnlyIdError';

/**
 * Error Response Body for Graph Delete API
 * @export
 * @interface GraphDeleteErrorResponse
 */
export interface GraphDeleteErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof GraphDeleteErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof GraphDeleteErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof GraphDeleteErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof GraphDeleteErrorResponse
   */
  chapter?: ChapterOnlyIdError;
  /**
   *
   * @type {SectionOnlyIdError}
   * @memberof GraphDeleteErrorResponse
   */
  section?: SectionOnlyIdError;
}

/**
 * Check if a given object implements the GraphDeleteErrorResponse interface.
 */
export function instanceOfGraphDeleteErrorResponse(value: object): value is GraphDeleteErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function GraphDeleteErrorResponseFromJSON(json: any): GraphDeleteErrorResponse {
  return GraphDeleteErrorResponseFromJSONTyped(json, false);
}

export function GraphDeleteErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphDeleteErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: json['chapter'] == null ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
    section: json['section'] == null ? undefined : SectionOnlyIdErrorFromJSON(json['section']),
  };
}

export function GraphDeleteErrorResponseToJSON(json: any): GraphDeleteErrorResponse {
  return GraphDeleteErrorResponseToJSONTyped(json, false);
}

export function GraphDeleteErrorResponseToJSONTyped(
  value?: GraphDeleteErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    chapter: ChapterOnlyIdErrorToJSON(value['chapter']),
    section: SectionOnlyIdErrorToJSON(value['section']),
  };
}
