/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphChildError } from './GraphChildError';
import {
  GraphChildErrorFromJSON,
  GraphChildErrorFromJSONTyped,
  GraphChildErrorToJSON,
  GraphChildErrorToJSONTyped,
} from './GraphChildError';

/**
 * Error Message for GraphChild list
 * @export
 * @interface GraphChildrenError
 */
export interface GraphChildrenError {
  /**
   * Error message for overall of children
   * @type {string}
   * @memberof GraphChildrenError
   */
  message?: string;
  /**
   *
   * @type {Array<GraphChildError>}
   * @memberof GraphChildrenError
   */
  items?: Array<GraphChildError>;
}

/**
 * Check if a given object implements the GraphChildrenError interface.
 */
export function instanceOfGraphChildrenError(value: object): value is GraphChildrenError {
  return true;
}

export function GraphChildrenErrorFromJSON(json: any): GraphChildrenError {
  return GraphChildrenErrorFromJSONTyped(json, false);
}

export function GraphChildrenErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphChildrenError {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
    items: json['items'] == null ? undefined : (json['items'] as Array<any>).map(GraphChildErrorFromJSON),
  };
}

export function GraphChildrenErrorToJSON(json: any): GraphChildrenError {
  return GraphChildrenErrorToJSONTyped(json, false);
}

export function GraphChildrenErrorToJSONTyped(
  value?: GraphChildrenError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    items: value['items'] == null ? undefined : (value['items'] as Array<any>).map(GraphChildErrorToJSON),
  };
}
