/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Graph object with only content fields
 * @export
 * @interface GraphContent
 */
export interface GraphContent {
  /**
   * Auto-generated section ID
   * @type {string}
   * @memberof GraphContent
   */
  id: string;
  /**
   * Graph paragraph
   * @type {string}
   * @memberof GraphContent
   */
  paragraph: string;
}

/**
 * Check if a given object implements the GraphContent interface.
 */
export function instanceOfGraphContent(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'paragraph' in value;

  return isInstance;
}

export function GraphContentFromJSON(json: any): GraphContent {
  return GraphContentFromJSONTyped(json, false);
}

export function GraphContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphContent {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    paragraph: json['paragraph'],
  };
}

export function GraphContentToJSON(value?: GraphContent | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    paragraph: value.paragraph,
  };
}
