/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Graph } from './Graph';
import { GraphFromJSON, GraphFromJSONTyped, GraphToJSON, GraphToJSONTyped } from './Graph';

/**
 * Response Body for Graph Sectionalize API
 * @export
 * @interface GraphSectionalizeResponse
 */
export interface GraphSectionalizeResponse {
  /**
   *
   * @type {Array<Graph>}
   * @memberof GraphSectionalizeResponse
   */
  graphs: Array<Graph>;
}

/**
 * Check if a given object implements the GraphSectionalizeResponse interface.
 */
export function instanceOfGraphSectionalizeResponse(value: object): value is GraphSectionalizeResponse {
  if (!('graphs' in value) || value['graphs'] === undefined) return false;
  return true;
}

export function GraphSectionalizeResponseFromJSON(json: any): GraphSectionalizeResponse {
  return GraphSectionalizeResponseFromJSONTyped(json, false);
}

export function GraphSectionalizeResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphSectionalizeResponse {
  if (json == null) {
    return json;
  }
  return {
    graphs: (json['graphs'] as Array<any>).map(GraphFromJSON),
  };
}

export function GraphSectionalizeResponseToJSON(json: any): GraphSectionalizeResponse {
  return GraphSectionalizeResponseToJSONTyped(json, false);
}

export function GraphSectionalizeResponseToJSONTyped(
  value?: GraphSectionalizeResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graphs: (value['graphs'] as Array<any>).map(GraphToJSON),
  };
}
