/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Graph object with only content fields without auto-generated fields
 * @export
 * @interface GraphContentWithoutAutofield
 */
export interface GraphContentWithoutAutofield {
  /**
   * Graph paragraph
   * @type {string}
   * @memberof GraphContentWithoutAutofield
   */
  paragraph: string;
}

/**
 * Check if a given object implements the GraphContentWithoutAutofield interface.
 */
export function instanceOfGraphContentWithoutAutofield(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'paragraph' in value;

  return isInstance;
}

export function GraphContentWithoutAutofieldFromJSON(json: any): GraphContentWithoutAutofield {
  return GraphContentWithoutAutofieldFromJSONTyped(json, false);
}

export function GraphContentWithoutAutofieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphContentWithoutAutofield {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    paragraph: json['paragraph'],
  };
}

export function GraphContentWithoutAutofieldToJSON(value?: GraphContentWithoutAutofield | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    paragraph: value.paragraph,
  };
}
