/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Graph } from './Graph';
import { GraphFromJSON, GraphFromJSONTyped, GraphToJSON, GraphToJSONTyped } from './Graph';

/**
 * Response Body for Graph Update API
 * @export
 * @interface GraphUpdateResponse
 */
export interface GraphUpdateResponse {
  /**
   *
   * @type {Graph}
   * @memberof GraphUpdateResponse
   */
  graph: Graph;
}

/**
 * Check if a given object implements the GraphUpdateResponse interface.
 */
export function instanceOfGraphUpdateResponse(value: object): value is GraphUpdateResponse {
  if (!('graph' in value) || value['graph'] === undefined) return false;
  return true;
}

export function GraphUpdateResponseFromJSON(json: any): GraphUpdateResponse {
  return GraphUpdateResponseFromJSONTyped(json, false);
}

export function GraphUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphUpdateResponse {
  if (json == null) {
    return json;
  }
  return {
    graph: GraphFromJSON(json['graph']),
  };
}

export function GraphUpdateResponseToJSON(json: any): GraphUpdateResponse {
  return GraphUpdateResponseToJSONTyped(json, false);
}

export function GraphUpdateResponseToJSONTyped(
  value?: GraphUpdateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value['graph']),
  };
}
