/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Graph object
 * @export
 * @interface Graph
 */
export interface Graph {
  /**
   * Auto-generated section ID
   * @type {string}
   * @memberof Graph
   */
  id: string;
  /**
   * Graph name
   * @type {string}
   * @memberof Graph
   */
  name: string;
  /**
   * Graph paragraph
   * @type {string}
   * @memberof Graph
   */
  paragraph: string;
}

/**
 * Check if a given object implements the Graph interface.
 */
export function instanceOfGraph(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'paragraph' in value;

  return isInstance;
}

export function GraphFromJSON(json: any): Graph {
  return GraphFromJSONTyped(json, false);
}

export function GraphFromJSONTyped(json: any, ignoreDiscriminator: boolean): Graph {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    paragraph: json['paragraph'],
  };
}

export function GraphToJSON(value?: Graph | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    paragraph: value.paragraph,
  };
}
