/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GraphContent } from './GraphContent';
import {
  GraphContentFromJSON,
  GraphContentFromJSONTyped,
  GraphContentToJSON,
  GraphContentToJSONTyped,
} from './GraphContent';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { ChapterOnlyId } from './ChapterOnlyId';
import {
  ChapterOnlyIdFromJSON,
  ChapterOnlyIdFromJSONTyped,
  ChapterOnlyIdToJSON,
  ChapterOnlyIdToJSONTyped,
} from './ChapterOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Graph Update API
 * @export
 * @interface GraphUpdateRequest
 */
export interface GraphUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof GraphUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof GraphUpdateRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {ChapterOnlyId}
   * @memberof GraphUpdateRequest
   */
  chapter: ChapterOnlyId;
  /**
   *
   * @type {GraphContent}
   * @memberof GraphUpdateRequest
   */
  graph: GraphContent;
}

/**
 * Check if a given object implements the GraphUpdateRequest interface.
 */
export function instanceOfGraphUpdateRequest(value: object): value is GraphUpdateRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  if (!('chapter' in value) || value['chapter'] === undefined) return false;
  if (!('graph' in value) || value['graph'] === undefined) return false;
  return true;
}

export function GraphUpdateRequestFromJSON(json: any): GraphUpdateRequest {
  return GraphUpdateRequestFromJSONTyped(json, false);
}

export function GraphUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterOnlyIdFromJSON(json['chapter']),
    graph: GraphContentFromJSON(json['graph']),
  };
}

export function GraphUpdateRequestToJSON(json: any): GraphUpdateRequest {
  return GraphUpdateRequestToJSONTyped(json, false);
}

export function GraphUpdateRequestToJSONTyped(
  value?: GraphUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
    chapter: ChapterOnlyIdToJSON(value['chapter']),
    graph: GraphContentToJSON(value['graph']),
  };
}
