/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
} from './ChapterOnlyIdError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { SectionOnlyIdError } from './SectionOnlyIdError';
import {
  SectionOnlyIdErrorFromJSON,
  SectionOnlyIdErrorFromJSONTyped,
  SectionOnlyIdErrorToJSON,
} from './SectionOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Graph Find API
 * @export
 * @interface GraphFindErrorResponse
 */
export interface GraphFindErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof GraphFindErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof GraphFindErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof GraphFindErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof GraphFindErrorResponse
   */
  chapter?: ChapterOnlyIdError;
  /**
   *
   * @type {SectionOnlyIdError}
   * @memberof GraphFindErrorResponse
   */
  section?: SectionOnlyIdError;
}

/**
 * Check if a given object implements the GraphFindErrorResponse interface.
 */
export function instanceOfGraphFindErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GraphFindErrorResponseFromJSON(json: any): GraphFindErrorResponse {
  return GraphFindErrorResponseFromJSONTyped(json, false);
}

export function GraphFindErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphFindErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: !exists(json, 'chapter') ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
    section: !exists(json, 'section') ? undefined : SectionOnlyIdErrorFromJSON(json['section']),
  };
}

export function GraphFindErrorResponseToJSON(value?: GraphFindErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterOnlyIdErrorToJSON(value.chapter),
    section: SectionOnlyIdErrorToJSON(value.section),
  };
}
