/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { ChapterOnlyId } from './ChapterOnlyId';
import {
  ChapterOnlyIdFromJSON,
  ChapterOnlyIdFromJSONTyped,
  ChapterOnlyIdToJSON,
  ChapterOnlyIdToJSONTyped,
} from './ChapterOnlyId';
import type { SectionWithoutAutofield } from './SectionWithoutAutofield';
import {
  SectionWithoutAutofieldFromJSON,
  SectionWithoutAutofieldFromJSONTyped,
  SectionWithoutAutofieldToJSON,
  SectionWithoutAutofieldToJSONTyped,
} from './SectionWithoutAutofield';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Graph Sectionalize API
 * @export
 * @interface GraphSectionalizeRequest
 */
export interface GraphSectionalizeRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {ChapterOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  chapter: ChapterOnlyId;
  /**
   *
   * @type {Array<SectionWithoutAutofield>}
   * @memberof GraphSectionalizeRequest
   */
  sections: Array<SectionWithoutAutofield>;
}

/**
 * Check if a given object implements the GraphSectionalizeRequest interface.
 */
export function instanceOfGraphSectionalizeRequest(value: object): value is GraphSectionalizeRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  if (!('chapter' in value) || value['chapter'] === undefined) return false;
  if (!('sections' in value) || value['sections'] === undefined) return false;
  return true;
}

export function GraphSectionalizeRequestFromJSON(json: any): GraphSectionalizeRequest {
  return GraphSectionalizeRequestFromJSONTyped(json, false);
}

export function GraphSectionalizeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphSectionalizeRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterOnlyIdFromJSON(json['chapter']),
    sections: (json['sections'] as Array<any>).map(SectionWithoutAutofieldFromJSON),
  };
}

export function GraphSectionalizeRequestToJSON(json: any): GraphSectionalizeRequest {
  return GraphSectionalizeRequestToJSONTyped(json, false);
}

export function GraphSectionalizeRequestToJSONTyped(
  value?: GraphSectionalizeRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
    chapter: ChapterOnlyIdToJSON(value['chapter']),
    sections: (value['sections'] as Array<any>).map(SectionWithoutAutofieldToJSON),
  };
}
