/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyId } from './ChapterOnlyId';
import { ChapterOnlyIdFromJSON, ChapterOnlyIdFromJSONTyped, ChapterOnlyIdToJSON } from './ChapterOnlyId';
import type { GraphContent } from './GraphContent';
import { GraphContentFromJSON, GraphContentFromJSONTyped, GraphContentToJSON } from './GraphContent';
import type { ProjectOnlyId } from './ProjectOnlyId';
import { ProjectOnlyIdFromJSON, ProjectOnlyIdFromJSONTyped, ProjectOnlyIdToJSON } from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Graph Update API
 * @export
 * @interface GraphUpdateRequest
 */
export interface GraphUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof GraphUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof GraphUpdateRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {ChapterOnlyId}
   * @memberof GraphUpdateRequest
   */
  chapter: ChapterOnlyId;
  /**
   *
   * @type {GraphContent}
   * @memberof GraphUpdateRequest
   */
  graph: GraphContent;
}

/**
 * Check if a given object implements the GraphUpdateRequest interface.
 */
export function instanceOfGraphUpdateRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'chapter' in value;
  isInstance = isInstance && 'graph' in value;

  return isInstance;
}

export function GraphUpdateRequestFromJSON(json: any): GraphUpdateRequest {
  return GraphUpdateRequestFromJSONTyped(json, false);
}

export function GraphUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphUpdateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterOnlyIdFromJSON(json['chapter']),
    graph: GraphContentFromJSON(json['graph']),
  };
}

export function GraphUpdateRequestToJSON(value?: GraphUpdateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectOnlyIdToJSON(value.project),
    chapter: ChapterOnlyIdToJSON(value.chapter),
    graph: GraphContentToJSON(value.graph),
  };
}
