/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
} from './ChapterOnlyIdError';
import type { GraphContentError } from './GraphContentError';
import {
  GraphContentErrorFromJSON,
  GraphContentErrorFromJSONTyped,
  GraphContentErrorToJSON,
} from './GraphContentError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Graph Update API
 * @export
 * @interface GraphUpdateErrorResponse
 */
export interface GraphUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof GraphUpdateErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof GraphUpdateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof GraphUpdateErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof GraphUpdateErrorResponse
   */
  chapter?: ChapterOnlyIdError;
  /**
   *
   * @type {GraphContentError}
   * @memberof GraphUpdateErrorResponse
   */
  graph?: GraphContentError;
}

/**
 * Check if a given object implements the GraphUpdateErrorResponse interface.
 */
export function instanceOfGraphUpdateErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GraphUpdateErrorResponseFromJSON(json: any): GraphUpdateErrorResponse {
  return GraphUpdateErrorResponseFromJSONTyped(json, false);
}

export function GraphUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphUpdateErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: !exists(json, 'chapter') ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
    graph: !exists(json, 'graph') ? undefined : GraphContentErrorFromJSON(json['graph']),
  };
}

export function GraphUpdateErrorResponseToJSON(value?: GraphUpdateErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterOnlyIdErrorToJSON(value.chapter),
    graph: GraphContentErrorToJSON(value.graph),
  };
}
