/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for GraphContent object
 * @export
 * @interface GraphContentError
 */
export interface GraphContentError {
  /**
   * Error message for graph ID
   * @type {string}
   * @memberof GraphContentError
   */
  id?: string;
  /**
   * Error message for graph paragraph
   * @type {string}
   * @memberof GraphContentError
   */
  paragraph?: string;
}

/**
 * Check if a given object implements the GraphContentError interface.
 */
export function instanceOfGraphContentError(value: object): value is GraphContentError {
  return true;
}

export function GraphContentErrorFromJSON(json: any): GraphContentError {
  return GraphContentErrorFromJSONTyped(json, false);
}

export function GraphContentErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphContentError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    paragraph: json['paragraph'] == null ? undefined : json['paragraph'],
  };
}

export function GraphContentErrorToJSON(json: any): GraphContentError {
  return GraphContentErrorToJSONTyped(json, false);
}

export function GraphContentErrorToJSONTyped(
  value?: GraphContentError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    paragraph: value['paragraph'],
  };
}
