/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Graph object with only content fields without auto-generated fields
 * @export
 * @interface GraphContentWithoutAutofield
 */
export interface GraphContentWithoutAutofield {
  /**
   * Graph paragraph
   * @type {string}
   * @memberof GraphContentWithoutAutofield
   */
  paragraph: string;
}

/**
 * Check if a given object implements the GraphContentWithoutAutofield interface.
 */
export function instanceOfGraphContentWithoutAutofield(value: object): value is GraphContentWithoutAutofield {
  if (!('paragraph' in value) || value['paragraph'] === undefined) return false;
  return true;
}

export function GraphContentWithoutAutofieldFromJSON(json: any): GraphContentWithoutAutofield {
  return GraphContentWithoutAutofieldFromJSONTyped(json, false);
}

export function GraphContentWithoutAutofieldFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphContentWithoutAutofield {
  if (json == null) {
    return json;
  }
  return {
    paragraph: json['paragraph'],
  };
}

export function GraphContentWithoutAutofieldToJSON(json: any): GraphContentWithoutAutofield {
  return GraphContentWithoutAutofieldToJSONTyped(json, false);
}

export function GraphContentWithoutAutofieldToJSONTyped(
  value?: GraphContentWithoutAutofield | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    paragraph: value['paragraph'],
  };
}
