/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyId } from './ChapterOnlyId';
import { ChapterOnlyIdFromJSON, ChapterOnlyIdFromJSONTyped, ChapterOnlyIdToJSON } from './ChapterOnlyId';
import type { ProjectOnlyId } from './ProjectOnlyId';
import { ProjectOnlyIdFromJSON, ProjectOnlyIdFromJSONTyped, ProjectOnlyIdToJSON } from './ProjectOnlyId';
import type { SectionWithoutAutofield } from './SectionWithoutAutofield';
import {
  SectionWithoutAutofieldFromJSON,
  SectionWithoutAutofieldFromJSONTyped,
  SectionWithoutAutofieldToJSON,
} from './SectionWithoutAutofield';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Graph Sectionalize API
 * @export
 * @interface GraphSectionalizeRequest
 */
export interface GraphSectionalizeRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {ChapterOnlyId}
   * @memberof GraphSectionalizeRequest
   */
  chapter: ChapterOnlyId;
  /**
   *
   * @type {Array<SectionWithoutAutofield>}
   * @memberof GraphSectionalizeRequest
   */
  sections: Array<SectionWithoutAutofield>;
}

/**
 * Check if a given object implements the GraphSectionalizeRequest interface.
 */
export function instanceOfGraphSectionalizeRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'chapter' in value;
  isInstance = isInstance && 'sections' in value;

  return isInstance;
}

export function GraphSectionalizeRequestFromJSON(json: any): GraphSectionalizeRequest {
  return GraphSectionalizeRequestFromJSONTyped(json, false);
}

export function GraphSectionalizeRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphSectionalizeRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterOnlyIdFromJSON(json['chapter']),
    sections: (json['sections'] as Array<any>).map(SectionWithoutAutofieldFromJSON),
  };
}

export function GraphSectionalizeRequestToJSON(value?: GraphSectionalizeRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectOnlyIdToJSON(value.project),
    chapter: ChapterOnlyIdToJSON(value.chapter),
    sections: (value.sections as Array<any>).map(SectionWithoutAutofieldToJSON),
  };
}
