/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for GraphContent object
 * @export
 * @interface GraphContentError
 */
export interface GraphContentError {
  /**
   * Error message for graph ID
   * @type {string}
   * @memberof GraphContentError
   */
  id?: string;
  /**
   * Error message for graph paragraph
   * @type {string}
   * @memberof GraphContentError
   */
  paragraph?: string;
}

/**
 * Check if a given object implements the GraphContentError interface.
 */
export function instanceOfGraphContentError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GraphContentErrorFromJSON(json: any): GraphContentError {
  return GraphContentErrorFromJSONTyped(json, false);
}

export function GraphContentErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphContentError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    paragraph: !exists(json, 'paragraph') ? undefined : json['paragraph'],
  };
}

export function GraphContentErrorToJSON(value?: GraphContentError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    paragraph: value.paragraph,
  };
}
