/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { SectionWithoutAutofieldListError } from './SectionWithoutAutofieldListError';
import {
  SectionWithoutAutofieldListErrorFromJSON,
  SectionWithoutAutofieldListErrorFromJSONTyped,
  SectionWithoutAutofieldListErrorToJSON,
  SectionWithoutAutofieldListErrorToJSONTyped,
} from './SectionWithoutAutofieldListError';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
  ChapterOnlyIdErrorToJSONTyped,
} from './ChapterOnlyIdError';

/**
 * Error Response Body for Graph Sectionalize API
 * @export
 * @interface GraphSectionalizeErrorResponse
 */
export interface GraphSectionalizeErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof GraphSectionalizeErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  chapter?: ChapterOnlyIdError;
  /**
   *
   * @type {SectionWithoutAutofieldListError}
   * @memberof GraphSectionalizeErrorResponse
   */
  sections?: SectionWithoutAutofieldListError;
}

/**
 * Check if a given object implements the GraphSectionalizeErrorResponse interface.
 */
export function instanceOfGraphSectionalizeErrorResponse(value: object): value is GraphSectionalizeErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function GraphSectionalizeErrorResponseFromJSON(json: any): GraphSectionalizeErrorResponse {
  return GraphSectionalizeErrorResponseFromJSONTyped(json, false);
}

export function GraphSectionalizeErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphSectionalizeErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: json['chapter'] == null ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
    sections: json['sections'] == null ? undefined : SectionWithoutAutofieldListErrorFromJSON(json['sections']),
  };
}

export function GraphSectionalizeErrorResponseToJSON(json: any): GraphSectionalizeErrorResponse {
  return GraphSectionalizeErrorResponseToJSONTyped(json, false);
}

export function GraphSectionalizeErrorResponseToJSONTyped(
  value?: GraphSectionalizeErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    chapter: ChapterOnlyIdErrorToJSON(value['chapter']),
    sections: SectionWithoutAutofieldListErrorToJSON(value['sections']),
  };
}
