/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
} from './ChapterOnlyIdError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { SectionWithoutAutofieldListError } from './SectionWithoutAutofieldListError';
import {
  SectionWithoutAutofieldListErrorFromJSON,
  SectionWithoutAutofieldListErrorFromJSONTyped,
  SectionWithoutAutofieldListErrorToJSON,
} from './SectionWithoutAutofieldListError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Graph Sectionalize API
 * @export
 * @interface GraphSectionalizeErrorResponse
 */
export interface GraphSectionalizeErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof GraphSectionalizeErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof GraphSectionalizeErrorResponse
   */
  chapter?: ChapterOnlyIdError;
  /**
   *
   * @type {SectionWithoutAutofieldListError}
   * @memberof GraphSectionalizeErrorResponse
   */
  sections?: SectionWithoutAutofieldListError;
}

/**
 * Check if a given object implements the GraphSectionalizeErrorResponse interface.
 */
export function instanceOfGraphSectionalizeErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function GraphSectionalizeErrorResponseFromJSON(json: any): GraphSectionalizeErrorResponse {
  return GraphSectionalizeErrorResponseFromJSONTyped(json, false);
}

export function GraphSectionalizeErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphSectionalizeErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: !exists(json, 'chapter') ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
    sections: !exists(json, 'sections') ? undefined : SectionWithoutAutofieldListErrorFromJSON(json['sections']),
  };
}

export function GraphSectionalizeErrorResponseToJSON(value?: GraphSectionalizeErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterOnlyIdErrorToJSON(value.chapter),
    sections: SectionWithoutAutofieldListErrorToJSON(value.sections),
  };
}
