/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HelloWorldRequest
 */
export interface HelloWorldRequest {
  /**
   * Your name
   * @type {string}
   * @memberof HelloWorldRequest
   */
  name?: string;
}

/**
 * Check if a given object implements the HelloWorldRequest interface.
 */
export function instanceOfHelloWorldRequest(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function HelloWorldRequestFromJSON(json: any): HelloWorldRequest {
  return HelloWorldRequestFromJSONTyped(json, false);
}

export function HelloWorldRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloWorldRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function HelloWorldRequestToJSON(value?: HelloWorldRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
