/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface HelloWorldResponse
 */
export interface HelloWorldResponse {
  /**
   * Hello message
   * @type {string}
   * @memberof HelloWorldResponse
   */
  message: string;
}

/**
 * Check if a given object implements the HelloWorldResponse interface.
 */
export function instanceOfHelloWorldResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'message' in value;

  return isInstance;
}

export function HelloWorldResponseFromJSON(json: any): HelloWorldResponse {
  return HelloWorldResponseFromJSONTyped(json, false);
}

export function HelloWorldResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HelloWorldResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: json['message'],
  };
}

export function HelloWorldResponseToJSON(value?: HelloWorldResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
  };
}
