/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PaperError } from './PaperError';
import { PaperErrorFromJSON, PaperErrorFromJSONTyped, PaperErrorToJSON } from './PaperError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Paper Update API
 * @export
 * @interface PaperUpdateErrorResponse
 */
export interface PaperUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof PaperUpdateErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof PaperUpdateErrorResponse
   */
  user: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof PaperUpdateErrorResponse
   */
  project: ProjectOnlyIdError;
  /**
   *
   * @type {PaperError}
   * @memberof PaperUpdateErrorResponse
   */
  paper: PaperError;
}

/**
 * Check if a given object implements the PaperUpdateErrorResponse interface.
 */
export function instanceOfPaperUpdateErrorResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'paper' in value;

  return isInstance;
}

export function PaperUpdateErrorResponseFromJSON(json: any): PaperUpdateErrorResponse {
  return PaperUpdateErrorResponseFromJSONTyped(json, false);
}

export function PaperUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaperUpdateErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: UserOnlyIdErrorFromJSON(json['user']),
    project: ProjectOnlyIdErrorFromJSON(json['project']),
    paper: PaperErrorFromJSON(json['paper']),
  };
}

export function PaperUpdateErrorResponseToJSON(value?: PaperUpdateErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    paper: PaperErrorToJSON(value.paper),
  };
}
