/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Paper object without auto-generated fields
 * @export
 * @interface PaperWithoutAutofield
 */
export interface PaperWithoutAutofield {
  /**
   * Paper content
   * @type {string}
   * @memberof PaperWithoutAutofield
   */
  content: string;
}

/**
 * Check if a given object implements the PaperWithoutAutofield interface.
 */
export function instanceOfPaperWithoutAutofield(value: object): value is PaperWithoutAutofield {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function PaperWithoutAutofieldFromJSON(json: any): PaperWithoutAutofield {
  return PaperWithoutAutofieldFromJSONTyped(json, false);
}

export function PaperWithoutAutofieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperWithoutAutofield {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
  };
}

export function PaperWithoutAutofieldToJSON(json: any): PaperWithoutAutofield {
  return PaperWithoutAutofieldToJSONTyped(json, false);
}

export function PaperWithoutAutofieldToJSONTyped(
  value?: PaperWithoutAutofield | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
  };
}
