/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyId } from './ChapterOnlyId';
import { ChapterOnlyIdFromJSON, ChapterOnlyIdFromJSONTyped, ChapterOnlyIdToJSON } from './ChapterOnlyId';
import type { ProjectOnlyId } from './ProjectOnlyId';
import { ProjectOnlyIdFromJSON, ProjectOnlyIdFromJSONTyped, ProjectOnlyIdToJSON } from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Paper Find API
 * @export
 * @interface PaperFindRequest
 */
export interface PaperFindRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof PaperFindRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof PaperFindRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {ChapterOnlyId}
   * @memberof PaperFindRequest
   */
  chapter: ChapterOnlyId;
}

/**
 * Check if a given object implements the PaperFindRequest interface.
 */
export function instanceOfPaperFindRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;
  isInstance = isInstance && 'chapter' in value;

  return isInstance;
}

export function PaperFindRequestFromJSON(json: any): PaperFindRequest {
  return PaperFindRequestFromJSONTyped(json, false);
}

export function PaperFindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    chapter: ChapterOnlyIdFromJSON(json['chapter']),
  };
}

export function PaperFindRequestToJSON(value?: PaperFindRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectOnlyIdToJSON(value.project),
    chapter: ChapterOnlyIdToJSON(value.chapter),
  };
}
