/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
  ChapterOnlyIdErrorToJSONTyped,
} from './ChapterOnlyIdError';

/**
 * Error Response Body for Paper Find API
 * @export
 * @interface PaperFindErrorResponse
 */
export interface PaperFindErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  chapter?: ChapterOnlyIdError;
}

/**
 * Check if a given object implements the PaperFindErrorResponse interface.
 */
export function instanceOfPaperFindErrorResponse(value: object): value is PaperFindErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function PaperFindErrorResponseFromJSON(json: any): PaperFindErrorResponse {
  return PaperFindErrorResponseFromJSONTyped(json, false);
}

export function PaperFindErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: json['chapter'] == null ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
  };
}

export function PaperFindErrorResponseToJSON(json: any): PaperFindErrorResponse {
  return PaperFindErrorResponseToJSONTyped(json, false);
}

export function PaperFindErrorResponseToJSONTyped(
  value?: PaperFindErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    chapter: ChapterOnlyIdErrorToJSON(value['chapter']),
  };
}
