/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Paper } from './Paper';
import { PaperFromJSON, PaperFromJSONTyped, PaperToJSON } from './Paper';

/**
 * Response Body for Paper Update API
 * @export
 * @interface PaperUpdateResponse
 */
export interface PaperUpdateResponse {
  /**
   *
   * @type {Paper}
   * @memberof PaperUpdateResponse
   */
  paper: Paper;
}

/**
 * Check if a given object implements the PaperUpdateResponse interface.
 */
export function instanceOfPaperUpdateResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'paper' in value;

  return isInstance;
}

export function PaperUpdateResponseFromJSON(json: any): PaperUpdateResponse {
  return PaperUpdateResponseFromJSONTyped(json, false);
}

export function PaperUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperUpdateResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    paper: PaperFromJSON(json['paper']),
  };
}

export function PaperUpdateResponseToJSON(value?: PaperUpdateResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    paper: PaperToJSON(value.paper),
  };
}
