/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for Paper object
 * @export
 * @interface PaperError
 */
export interface PaperError {
  /**
   * Error message for paper ID
   * @type {string}
   * @memberof PaperError
   */
  id?: string;
  /**
   * Error message for paper content
   * @type {string}
   * @memberof PaperError
   */
  content?: string;
}

/**
 * Check if a given object implements the PaperError interface.
 */
export function instanceOfPaperError(value: object): value is PaperError {
  return true;
}

export function PaperErrorFromJSON(json: any): PaperError {
  return PaperErrorFromJSONTyped(json, false);
}

export function PaperErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    content: json['content'] == null ? undefined : json['content'],
  };
}

export function PaperErrorToJSON(json: any): PaperError {
  return PaperErrorToJSONTyped(json, false);
}

export function PaperErrorToJSONTyped(value?: PaperError | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    content: value['content'],
  };
}
