/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Paper object
 * @export
 * @interface Paper
 */
export interface Paper {
  /**
   * Auto-generated paper ID
   * @type {string}
   * @memberof Paper
   */
  id: string;
  /**
   * Paper content
   * @type {string}
   * @memberof Paper
   */
  content: string;
}

/**
 * Check if a given object implements the Paper interface.
 */
export function instanceOfPaper(value: object): value is Paper {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function PaperFromJSON(json: any): Paper {
  return PaperFromJSONTyped(json, false);
}

export function PaperFromJSONTyped(json: any, ignoreDiscriminator: boolean): Paper {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    content: json['content'],
  };
}

export function PaperToJSON(json: any): Paper {
  return PaperToJSONTyped(json, false);
}

export function PaperToJSONTyped(value?: Paper | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    content: value['content'],
  };
}
