/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { Paper } from './Paper';
import { PaperFromJSON, PaperFromJSONTyped, PaperToJSON, PaperToJSONTyped } from './Paper';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Paper Update API
 * @export
 * @interface PaperUpdateRequest
 */
export interface PaperUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof PaperUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof PaperUpdateRequest
   */
  project: ProjectOnlyId;
  /**
   *
   * @type {Paper}
   * @memberof PaperUpdateRequest
   */
  paper: Paper;
}

/**
 * Check if a given object implements the PaperUpdateRequest interface.
 */
export function instanceOfPaperUpdateRequest(value: object): value is PaperUpdateRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  if (!('paper' in value) || value['paper'] === undefined) return false;
  return true;
}

export function PaperUpdateRequestFromJSON(json: any): PaperUpdateRequest {
  return PaperUpdateRequestFromJSONTyped(json, false);
}

export function PaperUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
    paper: PaperFromJSON(json['paper']),
  };
}

export function PaperUpdateRequestToJSON(json: any): PaperUpdateRequest {
  return PaperUpdateRequestToJSONTyped(json, false);
}

export function PaperUpdateRequestToJSONTyped(
  value?: PaperUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
    paper: PaperToJSON(value['paper']),
  };
}
