/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Paper } from './Paper';
import { PaperFromJSON, PaperFromJSONTyped, PaperToJSON, PaperToJSONTyped } from './Paper';

/**
 * Response Body for Paper Update API
 * @export
 * @interface PaperUpdateResponse
 */
export interface PaperUpdateResponse {
  /**
   *
   * @type {Paper}
   * @memberof PaperUpdateResponse
   */
  paper: Paper;
}

/**
 * Check if a given object implements the PaperUpdateResponse interface.
 */
export function instanceOfPaperUpdateResponse(value: object): value is PaperUpdateResponse {
  if (!('paper' in value) || value['paper'] === undefined) return false;
  return true;
}

export function PaperUpdateResponseFromJSON(json: any): PaperUpdateResponse {
  return PaperUpdateResponseFromJSONTyped(json, false);
}

export function PaperUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperUpdateResponse {
  if (json == null) {
    return json;
  }
  return {
    paper: PaperFromJSON(json['paper']),
  };
}

export function PaperUpdateResponseToJSON(json: any): PaperUpdateResponse {
  return PaperUpdateResponseToJSONTyped(json, false);
}

export function PaperUpdateResponseToJSONTyped(
  value?: PaperUpdateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    paper: PaperToJSON(value['paper']),
  };
}
