/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Response Body for Paper Find API
 * @export
 * @interface PaperFindErrorResponse
 */
export interface PaperFindErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  message: string;
  /**
   * Error message for user ID
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  userId?: string;
  /**
   * Error message for project ID
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  projectId?: string;
  /**
   * Error message for chapter ID
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  chapterId?: string;
}

/**
 * Check if a given object implements the PaperFindErrorResponse interface.
 */
export function instanceOfPaperFindErrorResponse(value: object): value is PaperFindErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function PaperFindErrorResponseFromJSON(json: any): PaperFindErrorResponse {
  return PaperFindErrorResponseFromJSONTyped(json, false);
}

export function PaperFindErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    userId: json['userId'] == null ? undefined : json['userId'],
    projectId: json['projectId'] == null ? undefined : json['projectId'],
    chapterId: json['chapterId'] == null ? undefined : json['chapterId'],
  };
}

export function PaperFindErrorResponseToJSON(json: any): PaperFindErrorResponse {
  return PaperFindErrorResponseToJSONTyped(json, false);
}

export function PaperFindErrorResponseToJSONTyped(
  value?: PaperFindErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    userId: value['userId'],
    projectId: value['projectId'],
    chapterId: value['chapterId'],
  };
}
