/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChapterOnlyIdError } from './ChapterOnlyIdError';
import {
  ChapterOnlyIdErrorFromJSON,
  ChapterOnlyIdErrorFromJSONTyped,
  ChapterOnlyIdErrorToJSON,
} from './ChapterOnlyIdError';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Paper Find API
 * @export
 * @interface PaperFindErrorResponse
 */
export interface PaperFindErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof PaperFindErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {ChapterOnlyIdError}
   * @memberof PaperFindErrorResponse
   */
  chapter?: ChapterOnlyIdError;
}

/**
 * Check if a given object implements the PaperFindErrorResponse interface.
 */
export function instanceOfPaperFindErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PaperFindErrorResponseFromJSON(json: any): PaperFindErrorResponse {
  return PaperFindErrorResponseFromJSONTyped(json, false);
}

export function PaperFindErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    chapter: !exists(json, 'chapter') ? undefined : ChapterOnlyIdErrorFromJSON(json['chapter']),
  };
}

export function PaperFindErrorResponseToJSON(value?: PaperFindErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectOnlyIdErrorToJSON(value.project),
    chapter: ChapterOnlyIdErrorToJSON(value.chapter),
  };
}
