/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Paper } from './Paper';
import { PaperFromJSON, PaperFromJSONTyped, PaperToJSON } from './Paper';

/**
 * Request Body for Paper Find API
 * @export
 * @interface PaperFindResponse
 */
export interface PaperFindResponse {
  /**
   *
   * @type {Paper}
   * @memberof PaperFindResponse
   */
  paper: Paper;
}

/**
 * Check if a given object implements the PaperFindResponse interface.
 */
export function instanceOfPaperFindResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'paper' in value;

  return isInstance;
}

export function PaperFindResponseFromJSON(json: any): PaperFindResponse {
  return PaperFindResponseFromJSONTyped(json, false);
}

export function PaperFindResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperFindResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    paper: PaperFromJSON(json['paper']),
  };
}

export function PaperFindResponseToJSON(value?: PaperFindResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    paper: PaperToJSON(value.paper),
  };
}
