/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for Paper object
 * @export
 * @interface PaperError
 */
export interface PaperError {
  /**
   * Error message for paper id
   * @type {string}
   * @memberof PaperError
   */
  id?: string;
  /**
   * Error message for paper content
   * @type {string}
   * @memberof PaperError
   */
  content?: string;
}

/**
 * Check if a given object implements the PaperError interface.
 */
export function instanceOfPaperError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PaperErrorFromJSON(json: any): PaperError {
  return PaperErrorFromJSONTyped(json, false);
}

export function PaperErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaperError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    content: !exists(json, 'content') ? undefined : json['content'],
  };
}

export function PaperErrorToJSON(value?: PaperError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    content: value.content,
  };
}
