/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyIdError } from './ProjectOnlyIdError';
import {
  ProjectOnlyIdErrorFromJSON,
  ProjectOnlyIdErrorFromJSONTyped,
  ProjectOnlyIdErrorToJSON,
  ProjectOnlyIdErrorToJSONTyped,
} from './ProjectOnlyIdError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';
import type { PaperError } from './PaperError';
import { PaperErrorFromJSON, PaperErrorFromJSONTyped, PaperErrorToJSON, PaperErrorToJSONTyped } from './PaperError';

/**
 * Error Response Body for Paper Update API
 * @export
 * @interface PaperUpdateErrorResponse
 */
export interface PaperUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof PaperUpdateErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof PaperUpdateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectOnlyIdError}
   * @memberof PaperUpdateErrorResponse
   */
  project?: ProjectOnlyIdError;
  /**
   *
   * @type {PaperError}
   * @memberof PaperUpdateErrorResponse
   */
  paper?: PaperError;
}

/**
 * Check if a given object implements the PaperUpdateErrorResponse interface.
 */
export function instanceOfPaperUpdateErrorResponse(value: object): value is PaperUpdateErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function PaperUpdateErrorResponseFromJSON(json: any): PaperUpdateErrorResponse {
  return PaperUpdateErrorResponseFromJSONTyped(json, false);
}

export function PaperUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PaperUpdateErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectOnlyIdErrorFromJSON(json['project']),
    paper: json['paper'] == null ? undefined : PaperErrorFromJSON(json['paper']),
  };
}

export function PaperUpdateErrorResponseToJSON(json: any): PaperUpdateErrorResponse {
  return PaperUpdateErrorResponseToJSONTyped(json, false);
}

export function PaperUpdateErrorResponseToJSONTyped(
  value?: PaperUpdateErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectOnlyIdErrorToJSON(value['project']),
    paper: PaperErrorToJSON(value['paper']),
  };
}
