/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for ProjectWithoutAutofield object
 * @export
 * @interface ProjectWithoutAutofieldError
 */
export interface ProjectWithoutAutofieldError {
  /**
   * Error message for project name
   * @type {string}
   * @memberof ProjectWithoutAutofieldError
   */
  name?: string;
  /**
   * Error message for project description
   * @type {string}
   * @memberof ProjectWithoutAutofieldError
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectWithoutAutofieldError interface.
 */
export function instanceOfProjectWithoutAutofieldError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProjectWithoutAutofieldErrorFromJSON(json: any): ProjectWithoutAutofieldError {
  return ProjectWithoutAutofieldErrorFromJSONTyped(json, false);
}

export function ProjectWithoutAutofieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectWithoutAutofieldError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
  };
}

export function ProjectWithoutAutofieldErrorToJSON(value?: ProjectWithoutAutofieldError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
  };
}
