/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Project object with only ID
 * @export
 * @interface ProjectOnlyId
 */
export interface ProjectOnlyId {
  /**
   * Auto-generated project ID
   * @type {string}
   * @memberof ProjectOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the ProjectOnlyId interface.
 */
export function instanceOfProjectOnlyId(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ProjectOnlyIdFromJSON(json: any): ProjectOnlyId {
  return ProjectOnlyIdFromJSONTyped(json, false);
}

export function ProjectOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlyId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ProjectOnlyIdToJSON(value?: ProjectOnlyId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
