/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON } from './Project';

/**
 * Response Body for Project Create API
 * @export
 * @interface ProjectCreateResponse
 */
export interface ProjectCreateResponse {
  /**
   *
   * @type {Project}
   * @memberof ProjectCreateResponse
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectCreateResponse interface.
 */
export function instanceOfProjectCreateResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'project' in value;

  return isInstance;
}

export function ProjectCreateResponseFromJSON(json: any): ProjectCreateResponse {
  return ProjectCreateResponseFromJSONTyped(json, false);
}

export function ProjectCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json['project']),
  };
}

export function ProjectCreateResponseToJSON(value?: ProjectCreateResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    project: ProjectToJSON(value.project),
  };
}
