/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON } from './Project';

/**
 * Response Body for Project List API
 * @export
 * @interface ProjectListResponse
 */
export interface ProjectListResponse {
  /**
   *
   * @type {Array<Project>}
   * @memberof ProjectListResponse
   */
  projects: Array<Project>;
}

/**
 * Check if a given object implements the ProjectListResponse interface.
 */
export function instanceOfProjectListResponse(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'projects' in value;

  return isInstance;
}

export function ProjectListResponseFromJSON(json: any): ProjectListResponse {
  return ProjectListResponseFromJSONTyped(json, false);
}

export function ProjectListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    projects: (json['projects'] as Array<any>).map(ProjectFromJSON),
  };
}

export function ProjectListResponseToJSON(value?: ProjectListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    projects: (value.projects as Array<any>).map(ProjectToJSON),
  };
}
