/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Project object without auto-generated fields
 * @export
 * @interface ProjectWithoutAutofield
 */
export interface ProjectWithoutAutofield {
  /**
   * Project name
   * @type {string}
   * @memberof ProjectWithoutAutofield
   */
  name: string;
  /**
   * Project description
   * @type {string}
   * @memberof ProjectWithoutAutofield
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectWithoutAutofield interface.
 */
export function instanceOfProjectWithoutAutofield(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;

  return isInstance;
}

export function ProjectWithoutAutofieldFromJSON(json: any): ProjectWithoutAutofield {
  return ProjectWithoutAutofieldFromJSONTyped(json, false);
}

export function ProjectWithoutAutofieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectWithoutAutofield {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
  };
}

export function ProjectWithoutAutofieldToJSON(value?: ProjectWithoutAutofield | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    description: value.description,
  };
}
