/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import { ProjectOnlyIdFromJSON, ProjectOnlyIdFromJSONTyped, ProjectOnlyIdToJSON } from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Project Find API
 * @export
 * @interface ProjectFindRequest
 */
export interface ProjectFindRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectFindRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof ProjectFindRequest
   */
  project: ProjectOnlyId;
}

/**
 * Check if a given object implements the ProjectFindRequest interface.
 */
export function instanceOfProjectFindRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;

  return isInstance;
}

export function ProjectFindRequestFromJSON(json: any): ProjectFindRequest {
  return ProjectFindRequestFromJSONTyped(json, false);
}

export function ProjectFindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectFindRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
  };
}

export function ProjectFindRequestToJSON(value?: ProjectFindRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectOnlyIdToJSON(value.project),
  };
}
