/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Project object with only ID
 * @export
 * @interface ProjectOnlyId
 */
export interface ProjectOnlyId {
  /**
   * Auto-generated project ID
   * @type {string}
   * @memberof ProjectOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the ProjectOnlyId interface.
 */
export function instanceOfProjectOnlyId(value: object): value is ProjectOnlyId {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function ProjectOnlyIdFromJSON(json: any): ProjectOnlyId {
  return ProjectOnlyIdFromJSONTyped(json, false);
}

export function ProjectOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlyId {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ProjectOnlyIdToJSON(json: any): ProjectOnlyId {
  return ProjectOnlyIdToJSONTyped(json, false);
}

export function ProjectOnlyIdToJSONTyped(value?: ProjectOnlyId | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
