/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request Parameters for Project Find API
 * @export
 * @interface ProjectFindRequest
 */
export interface ProjectFindRequest {
  /**
   * User ID
   * @type {string}
   * @memberof ProjectFindRequest
   */
  userId: string;
  /**
   * Auto-generated project ID
   * @type {string}
   * @memberof ProjectFindRequest
   */
  projectId: string;
}

/**
 * Check if a given object implements the ProjectFindRequest interface.
 */
export function instanceOfProjectFindRequest(value: object): value is ProjectFindRequest {
  if (!('userId' in value) || value['userId'] === undefined) return false;
  if (!('projectId' in value) || value['projectId'] === undefined) return false;
  return true;
}

export function ProjectFindRequestFromJSON(json: any): ProjectFindRequest {
  return ProjectFindRequestFromJSONTyped(json, false);
}

export function ProjectFindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectFindRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json['userId'],
    projectId: json['projectId'],
  };
}

export function ProjectFindRequestToJSON(json: any): ProjectFindRequest {
  return ProjectFindRequestToJSONTyped(json, false);
}

export function ProjectFindRequestToJSONTyped(
  value?: ProjectFindRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value['userId'],
    projectId: value['projectId'],
  };
}
