/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectOnlyId } from './ProjectOnlyId';
import {
  ProjectOnlyIdFromJSON,
  ProjectOnlyIdFromJSONTyped,
  ProjectOnlyIdToJSON,
  ProjectOnlyIdToJSONTyped,
} from './ProjectOnlyId';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Project Delete API
 * @export
 * @interface ProjectDeleteRequest
 */
export interface ProjectDeleteRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectDeleteRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectOnlyId}
   * @memberof ProjectDeleteRequest
   */
  project: ProjectOnlyId;
}

/**
 * Check if a given object implements the ProjectDeleteRequest interface.
 */
export function instanceOfProjectDeleteRequest(value: object): value is ProjectDeleteRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectDeleteRequestFromJSON(json: any): ProjectDeleteRequest {
  return ProjectDeleteRequestFromJSONTyped(json, false);
}

export function ProjectDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDeleteRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectOnlyIdFromJSON(json['project']),
  };
}

export function ProjectDeleteRequestToJSON(json: any): ProjectDeleteRequest {
  return ProjectDeleteRequestToJSONTyped(json, false);
}

export function ProjectDeleteRequestToJSONTyped(
  value?: ProjectDeleteRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectOnlyIdToJSON(value['project']),
  };
}
