/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for Project object
 * @export
 * @interface ProjectError
 */
export interface ProjectError {
  /**
   * Error message for project ID
   * @type {string}
   * @memberof ProjectError
   */
  id?: string;
  /**
   * Error message for project name
   * @type {string}
   * @memberof ProjectError
   */
  name?: string;
  /**
   * Error message for project description
   * @type {string}
   * @memberof ProjectError
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectError interface.
 */
export function instanceOfProjectError(value: object): value is ProjectError {
  return true;
}

export function ProjectErrorFromJSON(json: any): ProjectError {
  return ProjectErrorFromJSONTyped(json, false);
}

export function ProjectErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function ProjectErrorToJSON(json: any): ProjectError {
  return ProjectErrorToJSONTyped(json, false);
}

export function ProjectErrorToJSONTyped(value?: ProjectError | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
  };
}
