/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectWithoutAutofield } from './ProjectWithoutAutofield';
import {
  ProjectWithoutAutofieldFromJSON,
  ProjectWithoutAutofieldFromJSONTyped,
  ProjectWithoutAutofieldToJSON,
} from './ProjectWithoutAutofield';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Project Create API
 * @export
 * @interface ProjectCreateRequest
 */
export interface ProjectCreateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectCreateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectWithoutAutofield}
   * @memberof ProjectCreateRequest
   */
  project: ProjectWithoutAutofield;
}

/**
 * Check if a given object implements the ProjectCreateRequest interface.
 */
export function instanceOfProjectCreateRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;

  return isInstance;
}

export function ProjectCreateRequestFromJSON(json: any): ProjectCreateRequest {
  return ProjectCreateRequestFromJSONTyped(json, false);
}

export function ProjectCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectWithoutAutofieldFromJSON(json['project']),
  };
}

export function ProjectCreateRequestToJSON(value?: ProjectCreateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectWithoutAutofieldToJSON(value.project),
  };
}
