/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for ProjectWithoutAutofield object
 * @export
 * @interface ProjectWithoutAutofieldError
 */
export interface ProjectWithoutAutofieldError {
  /**
   * Error message for project name
   * @type {string}
   * @memberof ProjectWithoutAutofieldError
   */
  name?: string;
  /**
   * Error message for project description
   * @type {string}
   * @memberof ProjectWithoutAutofieldError
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectWithoutAutofieldError interface.
 */
export function instanceOfProjectWithoutAutofieldError(value: object): value is ProjectWithoutAutofieldError {
  return true;
}

export function ProjectWithoutAutofieldErrorFromJSON(json: any): ProjectWithoutAutofieldError {
  return ProjectWithoutAutofieldErrorFromJSONTyped(json, false);
}

export function ProjectWithoutAutofieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectWithoutAutofieldError {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function ProjectWithoutAutofieldErrorToJSON(json: any): ProjectWithoutAutofieldError {
  return ProjectWithoutAutofieldErrorToJSONTyped(json, false);
}

export function ProjectWithoutAutofieldErrorToJSONTyped(
  value?: ProjectWithoutAutofieldError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    description: value['description'],
  };
}
