/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON } from './Project';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON } from './UserOnlyId';

/**
 * Request Body for Project Update API
 * @export
 * @interface ProjectUpdateRequest
 */
export interface ProjectUpdateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectUpdateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {Project}
   * @memberof ProjectUpdateRequest
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectUpdateRequest interface.
 */
export function instanceOfProjectUpdateRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'user' in value;
  isInstance = isInstance && 'project' in value;

  return isInstance;
}

export function ProjectUpdateRequestFromJSON(json: any): ProjectUpdateRequest {
  return ProjectUpdateRequestFromJSONTyped(json, false);
}

export function ProjectUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectFromJSON(json['project']),
  };
}

export function ProjectUpdateRequestToJSON(value?: ProjectUpdateRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserOnlyIdToJSON(value.user),
    project: ProjectToJSON(value.project),
  };
}
