/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from './Project';

/**
 * Response Body for Project Create API
 * @export
 * @interface ProjectCreateResponse
 */
export interface ProjectCreateResponse {
  /**
   *
   * @type {Project}
   * @memberof ProjectCreateResponse
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectCreateResponse interface.
 */
export function instanceOfProjectCreateResponse(value: object): value is ProjectCreateResponse {
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectCreateResponseFromJSON(json: any): ProjectCreateResponse {
  return ProjectCreateResponseFromJSONTyped(json, false);
}

export function ProjectCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateResponse {
  if (json == null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json['project']),
  };
}

export function ProjectCreateResponseToJSON(json: any): ProjectCreateResponse {
  return ProjectCreateResponseToJSONTyped(json, false);
}

export function ProjectCreateResponseToJSONTyped(
  value?: ProjectCreateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value['project']),
  };
}
