/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from './Project';

/**
 * Response Body for Project Find API
 * @export
 * @interface ProjectFindResponse
 */
export interface ProjectFindResponse {
  /**
   *
   * @type {Project}
   * @memberof ProjectFindResponse
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectFindResponse interface.
 */
export function instanceOfProjectFindResponse(value: object): value is ProjectFindResponse {
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectFindResponseFromJSON(json: any): ProjectFindResponse {
  return ProjectFindResponseFromJSONTyped(json, false);
}

export function ProjectFindResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectFindResponse {
  if (json == null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json['project']),
  };
}

export function ProjectFindResponseToJSON(json: any): ProjectFindResponse {
  return ProjectFindResponseToJSONTyped(json, false);
}

export function ProjectFindResponseToJSONTyped(
  value?: ProjectFindResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value['project']),
  };
}
