/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request Parameters for Project List API
 * @export
 * @interface ProjectListRequest
 */
export interface ProjectListRequest {
  /**
   * User ID
   * @type {string}
   * @memberof ProjectListRequest
   */
  userId: string;
}

/**
 * Check if a given object implements the ProjectListRequest interface.
 */
export function instanceOfProjectListRequest(value: object): value is ProjectListRequest {
  if (!('userId' in value) || value['userId'] === undefined) return false;
  return true;
}

export function ProjectListRequestFromJSON(json: any): ProjectListRequest {
  return ProjectListRequestFromJSONTyped(json, false);
}

export function ProjectListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListRequest {
  if (json == null) {
    return json;
  }
  return {
    userId: json['userId'],
  };
}

export function ProjectListRequestToJSON(json: any): ProjectListRequest {
  return ProjectListRequestToJSONTyped(json, false);
}

export function ProjectListRequestToJSONTyped(
  value?: ProjectListRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value['userId'],
  };
}
