/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectError } from './ProjectError';
import {
  ProjectErrorFromJSON,
  ProjectErrorFromJSONTyped,
  ProjectErrorToJSON,
  ProjectErrorToJSONTyped,
} from './ProjectError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';

/**
 * Error Response Body for Project Update API
 * @export
 * @interface ProjectUpdateErrorResponse
 */
export interface ProjectUpdateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ProjectUpdateErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ProjectUpdateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectError}
   * @memberof ProjectUpdateErrorResponse
   */
  project?: ProjectError;
}

/**
 * Check if a given object implements the ProjectUpdateErrorResponse interface.
 */
export function instanceOfProjectUpdateErrorResponse(value: object): value is ProjectUpdateErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ProjectUpdateErrorResponseFromJSON(json: any): ProjectUpdateErrorResponse {
  return ProjectUpdateErrorResponseFromJSONTyped(json, false);
}

export function ProjectUpdateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectUpdateErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: json['project'] == null ? undefined : ProjectErrorFromJSON(json['project']),
  };
}

export function ProjectUpdateErrorResponseToJSON(json: any): ProjectUpdateErrorResponse {
  return ProjectUpdateErrorResponseToJSONTyped(json, false);
}

export function ProjectUpdateErrorResponseToJSONTyped(
  value?: ProjectUpdateErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
    project: ProjectErrorToJSON(value['project']),
  };
}
