/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProjectWithoutAutofieldError } from './ProjectWithoutAutofieldError';
import {
  ProjectWithoutAutofieldErrorFromJSON,
  ProjectWithoutAutofieldErrorFromJSONTyped,
  ProjectWithoutAutofieldErrorToJSON,
} from './ProjectWithoutAutofieldError';
import type { UserOnlyIdError } from './UserOnlyIdError';
import { UserOnlyIdErrorFromJSON, UserOnlyIdErrorFromJSONTyped, UserOnlyIdErrorToJSON } from './UserOnlyIdError';

/**
 * Error Response Body for Project Create API
 * @export
 * @interface ProjectCreateErrorResponse
 */
export interface ProjectCreateErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ProjectCreateErrorResponse
   */
  message?: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ProjectCreateErrorResponse
   */
  user?: UserOnlyIdError;
  /**
   *
   * @type {ProjectWithoutAutofieldError}
   * @memberof ProjectCreateErrorResponse
   */
  project?: ProjectWithoutAutofieldError;
}

/**
 * Check if a given object implements the ProjectCreateErrorResponse interface.
 */
export function instanceOfProjectCreateErrorResponse(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProjectCreateErrorResponseFromJSON(json: any): ProjectCreateErrorResponse {
  return ProjectCreateErrorResponseFromJSONTyped(json, false);
}

export function ProjectCreateErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectCreateErrorResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    user: !exists(json, 'user') ? undefined : UserOnlyIdErrorFromJSON(json['user']),
    project: !exists(json, 'project') ? undefined : ProjectWithoutAutofieldErrorFromJSON(json['project']),
  };
}

export function ProjectCreateErrorResponseToJSON(value?: ProjectCreateErrorResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    user: UserOnlyIdErrorToJSON(value.user),
    project: ProjectWithoutAutofieldErrorToJSON(value.project),
  };
}
