/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Project object without auto-generated fields
 * @export
 * @interface ProjectWithoutAutofield
 */
export interface ProjectWithoutAutofield {
  /**
   * Project name
   * @type {string}
   * @memberof ProjectWithoutAutofield
   */
  name: string;
  /**
   * Project description
   * @type {string}
   * @memberof ProjectWithoutAutofield
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectWithoutAutofield interface.
 */
export function instanceOfProjectWithoutAutofield(value: object): value is ProjectWithoutAutofield {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function ProjectWithoutAutofieldFromJSON(json: any): ProjectWithoutAutofield {
  return ProjectWithoutAutofieldFromJSONTyped(json, false);
}

export function ProjectWithoutAutofieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectWithoutAutofield {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function ProjectWithoutAutofieldToJSON(json: any): ProjectWithoutAutofield {
  return ProjectWithoutAutofieldToJSONTyped(json, false);
}

export function ProjectWithoutAutofieldToJSONTyped(
  value?: ProjectWithoutAutofield | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
    description: value['description'],
  };
}
