/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from './Project';

/**
 * Response Body for Project List API
 * @export
 * @interface ProjectListResponse
 */
export interface ProjectListResponse {
  /**
   *
   * @type {Array<Project>}
   * @memberof ProjectListResponse
   */
  projects: Array<Project>;
}

/**
 * Check if a given object implements the ProjectListResponse interface.
 */
export function instanceOfProjectListResponse(value: object): value is ProjectListResponse {
  if (!('projects' in value) || value['projects'] === undefined) return false;
  return true;
}

export function ProjectListResponseFromJSON(json: any): ProjectListResponse {
  return ProjectListResponseFromJSONTyped(json, false);
}

export function ProjectListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListResponse {
  if (json == null) {
    return json;
  }
  return {
    projects: (json['projects'] as Array<any>).map(ProjectFromJSON),
  };
}

export function ProjectListResponseToJSON(json: any): ProjectListResponse {
  return ProjectListResponseToJSONTyped(json, false);
}

export function ProjectListResponseToJSONTyped(
  value?: ProjectListResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    projects: (value['projects'] as Array<any>).map(ProjectToJSON),
  };
}
