/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Project List API
 * @export
 * @interface ProjectListRequest
 */
export interface ProjectListRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectListRequest
   */
  user: UserOnlyId;
}

/**
 * Check if a given object implements the ProjectListRequest interface.
 */
export function instanceOfProjectListRequest(value: object): value is ProjectListRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  return true;
}

export function ProjectListRequestFromJSON(json: any): ProjectListRequest {
  return ProjectListRequestFromJSONTyped(json, false);
}

export function ProjectListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectListRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
  };
}

export function ProjectListRequestToJSON(json: any): ProjectListRequest {
  return ProjectListRequestToJSONTyped(json, false);
}

export function ProjectListRequestToJSONTyped(
  value?: ProjectListRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
  };
}
