/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Error Message for ProjectOnlyId object
 * @export
 * @interface ProjectOnlyIdError
 */
export interface ProjectOnlyIdError {
  /**
   * Error message for project ID
   * @type {string}
   * @memberof ProjectOnlyIdError
   */
  id?: string;
}

/**
 * Check if a given object implements the ProjectOnlyIdError interface.
 */
export function instanceOfProjectOnlyIdError(value: object): value is ProjectOnlyIdError {
  return true;
}

export function ProjectOnlyIdErrorFromJSON(json: any): ProjectOnlyIdError {
  return ProjectOnlyIdErrorFromJSONTyped(json, false);
}

export function ProjectOnlyIdErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectOnlyIdError {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
  };
}

export function ProjectOnlyIdErrorToJSON(json: any): ProjectOnlyIdError {
  return ProjectOnlyIdErrorToJSONTyped(json, false);
}

export function ProjectOnlyIdErrorToJSONTyped(
  value?: ProjectOnlyIdError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
