/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserOnlyIdError } from './UserOnlyIdError';
import {
  UserOnlyIdErrorFromJSON,
  UserOnlyIdErrorFromJSONTyped,
  UserOnlyIdErrorToJSON,
  UserOnlyIdErrorToJSONTyped,
} from './UserOnlyIdError';

/**
 * Error Response Body for Project List API
 * @export
 * @interface ProjectListErrorResponse
 */
export interface ProjectListErrorResponse {
  /**
   * Error message when request body format is invalid
   * @type {string}
   * @memberof ProjectListErrorResponse
   */
  message: string;
  /**
   *
   * @type {UserOnlyIdError}
   * @memberof ProjectListErrorResponse
   */
  user?: UserOnlyIdError;
}

/**
 * Check if a given object implements the ProjectListErrorResponse interface.
 */
export function instanceOfProjectListErrorResponse(value: object): value is ProjectListErrorResponse {
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function ProjectListErrorResponseFromJSON(json: any): ProjectListErrorResponse {
  return ProjectListErrorResponseFromJSONTyped(json, false);
}

export function ProjectListErrorResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectListErrorResponse {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'],
    user: json['user'] == null ? undefined : UserOnlyIdErrorFromJSON(json['user']),
  };
}

export function ProjectListErrorResponseToJSON(json: any): ProjectListErrorResponse {
  return ProjectListErrorResponseToJSONTyped(json, false);
}

export function ProjectListErrorResponseToJSONTyped(
  value?: ProjectListErrorResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    user: UserOnlyIdErrorToJSON(value['user']),
  };
}
