/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for Project object
 * @export
 * @interface ProjectError
 */
export interface ProjectError {
  /**
   * Error message for project ID
   * @type {string}
   * @memberof ProjectError
   */
  id?: string;
  /**
   * Error message for project name
   * @type {string}
   * @memberof ProjectError
   */
  name?: string;
  /**
   * Error message for project description
   * @type {string}
   * @memberof ProjectError
   */
  description?: string;
}

/**
 * Check if a given object implements the ProjectError interface.
 */
export function instanceOfProjectError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function ProjectErrorFromJSON(json: any): ProjectError {
  return ProjectErrorFromJSONTyped(json, false);
}

export function ProjectErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
  };
}

export function ProjectErrorToJSON(value?: ProjectError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
  };
}
