/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectWithoutAutofield } from './ProjectWithoutAutofield';
import {
  ProjectWithoutAutofieldFromJSON,
  ProjectWithoutAutofieldFromJSONTyped,
  ProjectWithoutAutofieldToJSON,
  ProjectWithoutAutofieldToJSONTyped,
} from './ProjectWithoutAutofield';
import type { UserOnlyId } from './UserOnlyId';
import { UserOnlyIdFromJSON, UserOnlyIdFromJSONTyped, UserOnlyIdToJSON, UserOnlyIdToJSONTyped } from './UserOnlyId';

/**
 * Request Body for Project Create API
 * @export
 * @interface ProjectCreateRequest
 */
export interface ProjectCreateRequest {
  /**
   *
   * @type {UserOnlyId}
   * @memberof ProjectCreateRequest
   */
  user: UserOnlyId;
  /**
   *
   * @type {ProjectWithoutAutofield}
   * @memberof ProjectCreateRequest
   */
  project: ProjectWithoutAutofield;
}

/**
 * Check if a given object implements the ProjectCreateRequest interface.
 */
export function instanceOfProjectCreateRequest(value: object): value is ProjectCreateRequest {
  if (!('user' in value) || value['user'] === undefined) return false;
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectCreateRequestFromJSON(json: any): ProjectCreateRequest {
  return ProjectCreateRequestFromJSONTyped(json, false);
}

export function ProjectCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateRequest {
  if (json == null) {
    return json;
  }
  return {
    user: UserOnlyIdFromJSON(json['user']),
    project: ProjectWithoutAutofieldFromJSON(json['project']),
  };
}

export function ProjectCreateRequestToJSON(json: any): ProjectCreateRequest {
  return ProjectCreateRequestToJSONTyped(json, false);
}

export function ProjectCreateRequestToJSONTyped(
  value?: ProjectCreateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user: UserOnlyIdToJSON(value['user']),
    project: ProjectWithoutAutofieldToJSON(value['project']),
  };
}
