/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import { ProjectFromJSON, ProjectFromJSONTyped, ProjectToJSON, ProjectToJSONTyped } from './Project';

/**
 * Response Body for Project Update API
 * @export
 * @interface ProjectUpdateResponse
 */
export interface ProjectUpdateResponse {
  /**
   *
   * @type {Project}
   * @memberof ProjectUpdateResponse
   */
  project: Project;
}

/**
 * Check if a given object implements the ProjectUpdateResponse interface.
 */
export function instanceOfProjectUpdateResponse(value: object): value is ProjectUpdateResponse {
  if (!('project' in value) || value['project'] === undefined) return false;
  return true;
}

export function ProjectUpdateResponseFromJSON(json: any): ProjectUpdateResponse {
  return ProjectUpdateResponseFromJSONTyped(json, false);
}

export function ProjectUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateResponse {
  if (json == null) {
    return json;
  }
  return {
    project: ProjectFromJSON(json['project']),
  };
}

export function ProjectUpdateResponseToJSON(json: any): ProjectUpdateResponse {
  return ProjectUpdateResponseToJSONTyped(json, false);
}

export function ProjectUpdateResponseToJSONTyped(
  value?: ProjectUpdateResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    project: ProjectToJSON(value['project']),
  };
}
