/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for SectionOnlyId object
 * @export
 * @interface SectionOnlyIdError
 */
export interface SectionOnlyIdError {
  /**
   * Error message for section ID
   * @type {string}
   * @memberof SectionOnlyIdError
   */
  id?: string;
}

/**
 * Check if a given object implements the SectionOnlyIdError interface.
 */
export function instanceOfSectionOnlyIdError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SectionOnlyIdErrorFromJSON(json: any): SectionOnlyIdError {
  return SectionOnlyIdErrorFromJSONTyped(json, false);
}

export function SectionOnlyIdErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOnlyIdError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function SectionOnlyIdErrorToJSON(value?: SectionOnlyIdError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
