/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for SectionWithoutAutofield object
 * @export
 * @interface SectionWithoutAutofieldError
 */
export interface SectionWithoutAutofieldError {
  /**
   * Error message for section name
   * @type {string}
   * @memberof SectionWithoutAutofieldError
   */
  name?: string;
  /**
   * Error message for section content
   * @type {string}
   * @memberof SectionWithoutAutofieldError
   */
  content?: string;
}

/**
 * Check if a given object implements the SectionWithoutAutofieldError interface.
 */
export function instanceOfSectionWithoutAutofieldError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SectionWithoutAutofieldErrorFromJSON(json: any): SectionWithoutAutofieldError {
  return SectionWithoutAutofieldErrorFromJSONTyped(json, false);
}

export function SectionWithoutAutofieldErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SectionWithoutAutofieldError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    content: !exists(json, 'content') ? undefined : json['content'],
  };
}

export function SectionWithoutAutofieldErrorToJSON(value?: SectionWithoutAutofieldError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    content: value.content,
  };
}
