/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Section object in a Chapter object
 * @export
 * @interface SectionOfChapter
 */
export interface SectionOfChapter {
  /**
   * Auto-generated section ID
   * @type {string}
   * @memberof SectionOfChapter
   */
  id: string;
  /**
   * Section name
   * @type {string}
   * @memberof SectionOfChapter
   */
  name: string;
}

/**
 * Check if a given object implements the SectionOfChapter interface.
 */
export function instanceOfSectionOfChapter(value: object): value is SectionOfChapter {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function SectionOfChapterFromJSON(json: any): SectionOfChapter {
  return SectionOfChapterFromJSONTyped(json, false);
}

export function SectionOfChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOfChapter {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function SectionOfChapterToJSON(json: any): SectionOfChapter {
  return SectionOfChapterToJSONTyped(json, false);
}

export function SectionOfChapterToJSONTyped(
  value?: SectionOfChapter | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
  };
}
