/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionWithoutAutofieldError } from './SectionWithoutAutofieldError';
import {
  SectionWithoutAutofieldErrorFromJSON,
  SectionWithoutAutofieldErrorFromJSONTyped,
  SectionWithoutAutofieldErrorToJSON,
  SectionWithoutAutofieldErrorToJSONTyped,
} from './SectionWithoutAutofieldError';

/**
 * Error Message for SectionWithoutAutofield list
 * @export
 * @interface SectionWithoutAutofieldListError
 */
export interface SectionWithoutAutofieldListError {
  /**
   * Error message for overall of sections
   * @type {string}
   * @memberof SectionWithoutAutofieldListError
   */
  message?: string;
  /**
   *
   * @type {Array<SectionWithoutAutofieldError>}
   * @memberof SectionWithoutAutofieldListError
   */
  items?: Array<SectionWithoutAutofieldError>;
}

/**
 * Check if a given object implements the SectionWithoutAutofieldListError interface.
 */
export function instanceOfSectionWithoutAutofieldListError(value: object): value is SectionWithoutAutofieldListError {
  return true;
}

export function SectionWithoutAutofieldListErrorFromJSON(json: any): SectionWithoutAutofieldListError {
  return SectionWithoutAutofieldListErrorFromJSONTyped(json, false);
}

export function SectionWithoutAutofieldListErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SectionWithoutAutofieldListError {
  if (json == null) {
    return json;
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
    items: json['items'] == null ? undefined : (json['items'] as Array<any>).map(SectionWithoutAutofieldErrorFromJSON),
  };
}

export function SectionWithoutAutofieldListErrorToJSON(json: any): SectionWithoutAutofieldListError {
  return SectionWithoutAutofieldListErrorToJSONTyped(json, false);
}

export function SectionWithoutAutofieldListErrorToJSONTyped(
  value?: SectionWithoutAutofieldListError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value['message'],
    items: value['items'] == null ? undefined : (value['items'] as Array<any>).map(SectionWithoutAutofieldErrorToJSON),
  };
}
