/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SectionWithoutAutofieldError } from './SectionWithoutAutofieldError';
import {
  SectionWithoutAutofieldErrorFromJSON,
  SectionWithoutAutofieldErrorFromJSONTyped,
  SectionWithoutAutofieldErrorToJSON,
} from './SectionWithoutAutofieldError';

/**
 * Error Message for SectionWithoutAutofield list
 * @export
 * @interface SectionWithoutAutofieldListError
 */
export interface SectionWithoutAutofieldListError {
  /**
   * Error message for overall of sections
   * @type {string}
   * @memberof SectionWithoutAutofieldListError
   */
  message?: string;
  /**
   *
   * @type {Array<SectionWithoutAutofieldError>}
   * @memberof SectionWithoutAutofieldListError
   */
  items?: Array<SectionWithoutAutofieldError>;
}

/**
 * Check if a given object implements the SectionWithoutAutofieldListError interface.
 */
export function instanceOfSectionWithoutAutofieldListError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function SectionWithoutAutofieldListErrorFromJSON(json: any): SectionWithoutAutofieldListError {
  return SectionWithoutAutofieldListErrorFromJSONTyped(json, false);
}

export function SectionWithoutAutofieldListErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SectionWithoutAutofieldListError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    message: !exists(json, 'message') ? undefined : json['message'],
    items: !exists(json, 'items') ? undefined : (json['items'] as Array<any>).map(SectionWithoutAutofieldErrorFromJSON),
  };
}

export function SectionWithoutAutofieldListErrorToJSON(value?: SectionWithoutAutofieldListError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    message: value.message,
    items: value.items === undefined ? undefined : (value.items as Array<any>).map(SectionWithoutAutofieldErrorToJSON),
  };
}
