/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Section object with only ID
 * @export
 * @interface SectionOnlyId
 */
export interface SectionOnlyId {
  /**
   * Auto-generated section ID
   * @type {string}
   * @memberof SectionOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the SectionOnlyId interface.
 */
export function instanceOfSectionOnlyId(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function SectionOnlyIdFromJSON(json: any): SectionOnlyId {
  return SectionOnlyIdFromJSONTyped(json, false);
}

export function SectionOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOnlyId {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function SectionOnlyIdToJSON(value?: SectionOnlyId | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
