/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Section object in a Chapter object
 * @export
 * @interface SectionOfChapter
 */
export interface SectionOfChapter {
  /**
   * Auto-generated section ID
   * @type {string}
   * @memberof SectionOfChapter
   */
  id: string;
  /**
   * Section name
   * @type {string}
   * @memberof SectionOfChapter
   */
  name: string;
}

/**
 * Check if a given object implements the SectionOfChapter interface.
 */
export function instanceOfSectionOfChapter(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'name' in value;

  return isInstance;
}

export function SectionOfChapterFromJSON(json: any): SectionOfChapter {
  return SectionOfChapterFromJSONTyped(json, false);
}

export function SectionOfChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionOfChapter {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
  };
}

export function SectionOfChapterToJSON(value?: SectionOfChapter | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
