/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error Message for User object
 * @export
 * @interface UserError
 */
export interface UserError {
  /**
   * Error message for user ID
   * @type {string}
   * @memberof UserError
   */
  id?: string;
}

/**
 * Check if a given object implements the UserError interface.
 */
export function instanceOfUserError(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function UserErrorFromJSON(json: any): UserError {
  return UserErrorFromJSONTyped(json, false);
}

export function UserErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function UserErrorToJSON(value?: UserError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
