/* eslint-disable */
/**
 * Web API of kNODEledge
 * App to Create Graphically-Summarized Notes in Three Steps
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User object with only ID
 * @export
 * @interface UserOnlyId
 */
export interface UserOnlyId {
  /**
   * User ID
   * @type {string}
   * @memberof UserOnlyId
   */
  id: string;
}

/**
 * Check if a given object implements the UserOnlyId interface.
 */
export function instanceOfUserOnlyId(value: object): value is UserOnlyId {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function UserOnlyIdFromJSON(json: any): UserOnlyId {
  return UserOnlyIdFromJSONTyped(json, false);
}

export function UserOnlyIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOnlyId {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function UserOnlyIdToJSON(json: any): UserOnlyId {
  return UserOnlyIdToJSONTyped(json, false);
}

export function UserOnlyIdToJSONTyped(value?: UserOnlyId | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
