name: Push

on:
  push:
    branches: [main]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Run unittest
        uses: ./.github/workflows/reusable-unittest.yml
  release:
    needs: unittest
    runs-on: ubuntu-latest
    steps:
      - name: Run staging release
        uses: ./.github/workflows/reusable-release.yml
