name: Push

on:
  push:
    branches: [main]
jobs:
  unittest:
    uses: ./.github/workflows/reusable-unittest.yml
  release:
    needs: unittest
    uses: ./.github/workflows/reusable-release.yml
  ghpages:
    needs: [release]
    uses: ./.github/workflows/reusable-ghpages.yml
